### ISSUE TITLE
Data size sent to server is not correct

### ISSUE THREAD

**Issue by mustafakasap** [bojand/ghz#100]
**Proto file(s)**
_syntax = "proto3";

package inferer;

service Inferer {
  rpc infer(stream Request) returns (Reply) {}
}

message Request {
  bytes content = 1;
}

message Reply {
  string message = 1;
}_

**Command line arguments / config**
  _./ghz \
  --insecure \
  --proto /Users/mkasap/Documents/iovis/client/c++/inference_service.proto \
  --call inferer.Inferer.infer \
  192.168.2.20:50051 < /Users/mkasap/Documents/iovis/test/data/sample01.jpg_

**Describe the bug**
_I am not sure if I use the parameters correctly but file size of "sample01.jpg" is 600Kb. But when I check the network traffic, only 10Kb data sent. ghz command ouput seems all went well but it is not sending the whole data to the server.

output of the "ghz" code is (but only 10KB data sent to the server):
mk44tr-mac-office:ghzgrpc mkasap$ ./ghz   --insecure   --proto /Users/mkasap/Documents/iovis/client/c++/inference_service.proto   --call inferer.Inferer.infer   192.168.2.20:50051 < /Users/mkasap/Documents/iovis/test/data/sample01.jpg

Summary:
  Count:	200
  Total:	207.85 ms
  Slowest:	71.99 ms
  Fastest:	13.55 ms
  Average:	46.31 ms
  Requests/sec:	962.23

Response time histogram:
  13.547 [1]	|∎
  19.391 [6]	|∎∎∎∎
  25.235 [3]	|∎∎
  31.080 [6]	|∎∎∎∎
  36.924 [11]	|∎∎∎∎∎∎
  42.768 [21]	|∎∎∎∎∎∎∎∎∎∎∎∎
  48.612 [57]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  54.456 [68]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  60.300 [24]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  66.144 [1]	|∎
  71.988 [2]	|∎

Latency distribution:
  10% in 33.56 ms
  25% in 43.43 ms
  50% in 48.21 ms
  75% in 52.22 ms
  90% in 55.16 ms
  95% in 57.10 ms
  99% in 71.62 ms

Status code distribution:
  [OK]   200 responses_

**To Reproduce**

**Expected behavior**

**Environment**
 - OS: macOS 10.14.5
 - ghz: 0.37.0
 
**Screenshots**

**Additional context**

**Comment by bojand** [comment]
Hello,

Your request is a protobuf message:

```proto
message Request {
  bytes content = 1;
}
```
I am assuming `content` field is the image data.

You cannot just simply use the image as input, you have to input the whole `Request` message.

For actual message data you should be able to use the `-B` (binary) option. Simply [serialize the whole](https://developers.google.com/protocol-buffers/docs/gotutorial#writing-a-message) message to a file first. Then use the file with `-B ./my_message.bin` for example. This is usually more practical when having to deal with some of the message having binary data.

Alternatively you can try and input the request as JSON data but [use base64 string](https://developers.google.com/protocol-buffers/docs/proto3#json) representation of the image as the value for the `content` field.

```
-d '{"content":"... base64 encoding of the image"}' 
```

Hope this helps.
