### ISSUE TITLE
How to upload the message including multi sub-message?

### ISSUE THREAD

**Issue by qinb** [bojand/ghz#101]
**Is your feature request related to a problem? Please describe.**
My part of proto format is as following:
```
 service ocr_service {
  rpc ocr_infer(ImageRequest) returns (JsonResponse);
}

message Image {
    // *Required*. Picture encoding format.
    string strImageFormats = 1;
    // *Required*. Image binary file.
    bytes imageData = 2;
}
message HttpInfos {
    string strHid        = 1;
    string strVersion    = 2;
    string strIMERegion  = 3;
    string strRegion     = 4;
    int32  nAction       = 5;
    int32  nPiWidth      = 6;
    int32  nPiHeight     = 7;
    int32  nSplit        = 8;
}

message ImageRequest {
    // *Required*. Template image.
    Image img = 1;
    HttpInfos hpinfos = 2;
}

message JsonResponse {
  string strResult = 1;
}
 ```

**Describe the solution you'd like**
Now ,I want to upload necessary datas by the ghz cli
ghz --insecure --proto ocr.proto --call v1.ocr_service.ocr_infer 0.0.0.0:9999 -d ?

I don't know how to datas, Can you help me ? Thanks @bojand @nlohmann @kenju @pedgeio @tab1293

**Comment by bojand** [comment]
Hello,

This has been asked before in #100 and #44.

You should be able to use the `-B` (binary) option. Simply [serialize the whole](https://developers.google.com/protocol-buffers/docs/gotutorial#writing-a-message) message to a file first. Then use the file with `-B ./my_message.bin` for example. This is usually more practical when having to deal with some of the message having binary data.

Alternatively you can try and input the request as JSON data but [use base64 string](https://developers.google.com/protocol-buffers/docs/proto3#json) representation of the image as the value for the `imageData` field.

```
-d '{"content":"... base64 encoding of the image ..."}' 
```

I'll try and document this with some examples in documentation.

Hope this helps.

**Comment by pedgeio** [comment]
Please do not "@" people in GitHub issues - I, along with most of the people above, are not maintainers of this library, and it is even discourteous to "@" a maintainer. Thanks!
