### ISSUE TITLE
Question: how can we generate a constant load per second

### ISSUE THREAD

**Issue by sauravkumar05** [bojand/ghz#105]
Let’s say I want to generate a load of 1000 request per second for a duration of 60 seconds how can I achieve that . I wasn’t able to generate constant load every time I run . I can see max duration with n or total number of request or sending load just based on duration but didn’t see a way to generate a set of request where we are able to send the same request per second

**Comment by ezsilmar** [comment]
Hello, 
Have you tried a [qps](https://ghz.sh/docs/options#q-qps) option? Also you should probably increase [concurrency](https://ghz.sh/docs/options#c-concurrency) to achieve desired qps.

**Comment by minddazed** [comment]
1. Baseline latency (e.g. p95 latency = 400ms)
2. Set qps (e.g. qps < 1000/latency)
3. Set concurrency (concurrency = desired rps/qps)

Duration will just be however long you want the test to run.
