### ISSUE TITLE
failed: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by inewlife** [bojand/ghz#107]
failed: tls: first record does not look like a TLS handshake

macOs

`./ghz -insecure \
--proto ./call.proto \
--call protobuf.RemoteCall.get_result \
-d '{"method_name":"detectCenter","arg":"ddd"}' \
10.21.2.20:8811`

**Comment by bojand** [comment]
Hello, are you sure you are running server in insecure mode?
