### ISSUE TITLE
failed to load imports for proto by checking an invalid directory

### ISSUE THREAD

**Issue by ekj1711** [bojand/ghz#112]
**Proto file(s)**
my proto file --> abcd.proto in path **"/Users/user/go/src/mygit/myproj/subproj/proto/component/abcd.proto"**
imports a proto file annotations.proto. 
[abcd.proto]
import **"google/api/annotations.proto";**
.
.
.

[annotations.proto]
import "google/api/http.proto";
import "google/protobuf/descriptor.proto";

I have downloaded the source for annotations.proto & descriptor.proto in custom paths in my file system which is in the following directories respectively.

"i": [
                "/Users/user/go/src/github.com/googleapis",
                "/Users/user/Downloads/protoc-3.9.0-osx-x86_64/include"
        ]

**Command line arguments / config**
List all command line arguments or config properties
using the command, "ghz --config myconfig.json" returns the error,
**failed to load imports** for "abcd.proto": open /Users/user/go/src/mygit/myproj/subproj/proto/component/google/api/annotations.proto: no such file or directory

**Describe the bug**
The import (-i) seems not working for me as it is not looking for the dependency in the custom path provided. It is looking for dependency in the same package's sub-directory where the proto file is present. 

**To Reproduce**
a. Download the dependency proto files in a custom path 
b. create a config.json file which specifies the proto file and its dependencies. 
a. run ghz with the config json file. 
d. error stating  no such file or directory as it is looking for dependencies in a path ( .proto file path + import path mentioned in that proto file). In above example, it is creating the path for annotations.proto in **/Users/user/go/src/mygit/myproj/subproj/proto/component/google/api/annotations.proto**

**Expected behavior**
Expected to resolve the dependency loading of .proto file.

**Environment**
 - OS: macOS
 - ghz: 0.39.0

**Comment by bojand** [comment]
Hello can you please provide more information, or ideally reproducible repository. the config specifies `"/Users/user/go/src/github.com/googleapis"` as an import path, but it's erroring out tryng to find `...component/google/api/annotations.proto` so something is not lining up with where the files are and the import paths (within protos) and import paths specified in config. I am guessing the google api protos are not in the "correct" location for the other respective params.
