### ISSUE TITLE
Timeout config option documention

### ISSUE THREAD

**Issue by KnutZuidema** [bojand/ghz#117]
**Proto file(s)**
none

**Command line arguments / config**
`-t` / `--timeout`

**Describe the bug**
The docs on the website and in the README say that the timeout is an integer representing seconds, however in a recent commit (https://github.com/bojand/ghz/commit/6215cc8b8c7b6e0e0267dcff54ed7f5f73fddf5b#diff-b55584fa8db397e5751ba4fdc23e10d7R50) this was changed to a duration string.

**To Reproduce**
use an integer for timeout in the configuration

**Expected behavior**
I expect the integer to work, however it produces an error message:
`ghz: error: json: cannot unmarshal number into Go struct field .timeout of type string`

**Environment**
any

**Comment by bojand** [comment]
Hello thanks for pointing this out. I failed to update the documentation for this. Please use a duration string such as `5s` and that should work. I will update the documentation soon.

**Comment by KnutZuidema** [comment]
I already did that, just figured I'd mention it here, because it caused our CI pipeline to fail :+1:
