### ISSUE TITLE
Add support for authorization headers

### ISSUE THREAD

**Issue by ashwinr89** [bojand/ghz#120]
**Is your feature request related to a problem? Please describe.**
Yes. The service that we use verifies the Oauth2 token (bearer token) in the header.

**Describe the solution you'd like**
It would be better to have an option for specifying the token directly or authorization header.

**Describe alternatives you've considered**
No alternatives. 

**Additional context**
The grpcurl supports `rpc-header` where the token can be passed in.
```
-rpc-header "authorization: Bearer ${TOKEN}"
```

**Comment by bojand** [comment]
Hello,

This should be possible using [metadata](https://ghz.sh/docs/options#m-metadata) option.  `grpcurl` [converts](https://github.com/fullstorydev/grpcurl/blob/master/grpcurl.go#L143) the "headers" to grpc [metadata](https://grpc.io/docs/guides/concepts/#metadata). For example something like the following should work:

```
ghz -m '{"authorization":"Bearer ${TOKEN}"}' ...
```

Hope this helps.

**Comment by ashwinr89** [comment]
Thank you. That helps.
