### ISSUE TITLE
Does response time include download time?

### ISSUE THREAD

**Issue by gulinfu** [bojand/ghz#125]
1. Does response time include response download time if I have a large size response? Or it's just time to first byte?
2. Is it possible to print out the response for some query?

Thanks!

**Comment by bojand** [comment]
Hello,

1. With regards to stats measured, we use [WithStatsHandler](https://godoc.org/google.golang.org/grpc#WithStatsHandler) options to capture call stats. Specifically we only capture the [End](https://godoc.org/google.golang.org/grpc/stats#End) event which contains stats when an RPC ends. My understanding is that this should include the download of the payload and deserializing of the data. Basically, for unary calls for example, the order of call stats events is:

```
Begin
OutHeader
OutPayload
InHeader
InPayload
InTrailer
End
```

This measurement was chosen as it more accurately represents the total lag clients would experience until they can use the call response, so I thought it was a more meaningful data point.

2. Right now, no there is no mechanism of logging the data from the server. This may be possible with some kind of debug option where we can log to a debug file events and data received.

Hope this clears things up.
