### ISSUE TITLE
Error logs mangle return error message

### ISSUE THREAD

**Issue by tp** [bojand/ghz#126]
**Describe the bug**
We have an error message that includes an encoded URLs. In `ghz` that seems to be used in a format string and hence leading to this output:

```
Error distribution:
  [20000]   rpc error: code = Unknown desc = Non-success status code 401 for https://host.com/api/outfits/v1?appId=10&outfitIds%!B(MISSING)%!D(MISSING)%!B(MISSING)%!D(MISSING)=10569&outfitIds%!B(MISSING)%!D(MISSING)%!B(MISSING)%!D(MISSING)=10570&outfitIds%!B(MISSING)%!D(MISSING)%!B(MISSING)%!D(MISSING)=10568&outfitIds%!B(MISSING)%!D(MISSING)%!B(MISSING)%!D(MISSING)=10561&outfitIds%!B(MISSING)%!D(MISSING)%!B(MISSING)%!D(MISSING)=10564&outfitIds%!B(MISSING)%!D(MISSING)%!B(MISSING)%!D(MISS
```

**To Reproduce**

Return an error message with `%` in it

**Expected behavior**

Should log the error message verbatim

**Environment**
 - OS: 10.14.6
 - ghz: 0.41.0
 
**Screenshots**

<img width="588" alt="image" src="https://user-images.githubusercontent.com/52437/64251542-13831300-cf19-11e9-9565-202fdf22f770.png">

In BloomRPC for example the response looks just fine:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/52437/64251528-0d8d3200-cf19-11e9-9d9a-1aca0d42383f.png">

**Additional context**

**Comment by tp** [comment]
I had a quick look into this codebase but couldn't easily spot the file that prints this.

Looks pretty clear what kind of string build / formatting would cause this, if you can point me into the right direction I can have a stab at fixing the issue as well.

**Comment by bojand** [comment]
Hmm that's not very useful. It might be something to do with how we [print](https://github.com/bojand/ghz/blob/master/printer/printer.go#L35) errors using the default [template](https://github.com/bojand/ghz/blob/master/printer/printer.go#L369). I will try and take a look soon when I get a bit more time.

**Comment by tp** [comment]
@bojand Isn't is just this line: https://github.com/bojand/ghz/blob/master/printer/printer.go#L46 ?

```
return rp.printf(buf.String())
```

I guess if you change that from `printf` to `print` it will be fine.
