### ISSUE TITLE
[WebUI] Multi-Select and Delete reports

### ISSUE THREAD

**Issue by resec** [bojand/ghz#127]
**Is your feature request related to a problem? Please describe.**
It's very troublesome when I uploaded many reports and want to delete some of them.

**Describe the solution you'd like**
A method in web-ui to multi-select reports and deletes.

**Describe alternatives you've considered**
Maybe a method to filter reports by tags

**Additional context**
Maybe filtering seems better choice, but there will be always a need to delete at some point.

**Comment by bojand** [comment]
Hello, this should be implemented in [0.43.0](https://github.com/bojand/ghz/releases/tag/v0.43.0). If there are any problems feel free to create new issues.
