### ISSUE TITLE
Use Template on Binary File Mode

### ISSUE THREAD

**Issue by reddol18** [bojand/ghz#128]
I ran the test by specifying the template variable like "{{.RequestNumber}}" in the binary file. 

In the case of a json file, the value is correctly converted and passed, but in the case of a binary file, the value above seems to be passed as it is. 

Is there a way to support templates even for binary files? If not, it would be added as a new feature

**Comment by bojand** [comment]
Hello, the template variables are only supported with JSON data, and not with binary data. This is not something that can be accomplished really as it uses [text/template](https://golang.org/pkg/text/template/) which is only usable with textual data..
