### ISSUE TITLE
Using config as default and CLI flag as overrides

### ISSUE THREAD

**Issue by minddazed** [bojand/ghz#136]
**Is your feature request related to a problem? Please describe.**
I'd like to use the CLI flags to override default parameters set in a config file. 

**Describe the solution you'd like**
For example duration is something I often change between tests. I would like to specify a default value in the config file, e.g. in data.json "duration=10m", but then override this value if I pass it in as a flag on the command, e.g. "ghz --config=data.json -z 1m"

This is particularly useful when I want to change the duration of a test script where I batch ghz load tests to simulate multiple GRPC method calls to a single service.

#!/usr/bin/env bash
DURATION="1m"

ghz --config=getByName.json -z $DURATION > report1.html &
ghz --config=getById.json -z $DURATION > report2.html &
ghz --config=sendName.json -z $DURATION > report3.html

**Additional context**
I've tried this against the current ghz build and it does not seem to be supported.

**Comment by bojand** [comment]
Hello this should be implemented now in [0.46.0](https://github.com/bojand/ghz/releases/tag/v0.46.0). Feel free to create new issue if there are any problems.
