### ISSUE TITLE
Can ghz print gRPC output on the command line?

### ISSUE THREAD

**Issue by hq6** [bojand/ghz#149]
I am running ghz against an application returns errors as error codes at the application-level, inside the response, rather than throwing an exception. Unfortunately, since `ghz` simply outputs `OK` for any completed request, I cannot tell whether the correct arguments are being passed to the application.

Is there a way to get the proto output of the request from ghz?

**Comment by bojand** [comment]
Hello, ghz assumes you are familiar with the server implementation and are able to make correct calls, or intentionally making incorrect ones.
Right now there is no way to print out the data sent and received from server. This has been inquired about before so it may be a good feature to add debug logging option.
