### ISSUE TITLE
The possibility to exclude the histogram from the json output

### ISSUE THREAD

**Issue by SeriyBg** [bojand/ghz#151]
**Is your feature request related to a problem? Please describe.**
I'm running about 10_000 requests and I'm interested in the latency distribution in the first place. However, the histogram is huge and in the console output.

**Describe the solution you'd like**
One possible solution would be having sort of flag as `output-exclude` or similar

**Comment by bojand** [comment]
You could use [jq](https://stedolan.github.io/jq/) and delete whatever data you do not need. Something like `del(.histogram)|del(.details)` should delete `histogram` and `details` properties. Hope this helps.

**Comment by SeriyBg** [comment]
@bojand thanks, that's what I'm using now. I thought that I would be useful to have configurable output without using an extra tool
