### ISSUE TITLE
How to build this project ?

### ISSUE THREAD

**Issue by bryanhuntesl** [bojand/ghz#156]
I'd like to build the ghz executable - I always prefer to build or download from homebrew rather than install binaries from github but I can't quite figure out how to build this tool. 

Any hints? Happy to create a nice docs PR to help others.

**Comment by craigh1015** [comment]
I have go 1.13.6 installed - the following worked for me
``` bash
git clone https://github.com/bojand/ghz.git
cd ghz/cmd/ghz
go build
```

**Comment by bojand** [comment]
Yup as @craigh1015 recommends, that's the standard way to build from source with Go. For a release build use the linker flags:
```
go build -ldflags="-s -w"
```
