### ISSUE TITLE
Generate stable and predictable ID for a grpc request.

### ISSUE THREAD

**Issue by PeterFras** [bojand/ghz#159]
**Is your feature request related to a problem? Please describe.**

I would like to run a load test for Cassandra database fronted by a gRPC service using ghz. The gRPC service queries Cassandra for a document by an ID.

I use {{ .RequestNumber}} to generate document ID. The generated ID has really bad distribution (because it's sequential), hence the test doesn't exercise whole cluster.

For test to be meaningful, the ID needs to be stable, predictable and have good distribution.

**Describe the solution you'd like**
I'd like ghz to generate the stable identifier for a request - possibly UUID v3 (from request number).

**Describe alternatives you've considered**
ghz to take list of ID's in form of a file.

I am happy to contribute to the project with proposed solution.

**Comment by bojand** [comment]
Hello, the call template data does provide UUID (version 4) property. Is this not sufficient for your needs? It is not sourced the same as v3 and predictable in that sense, but in theory it should provide a good distribution. Is this not sufficient or appropriate for your use case?

I am not sure how you run the tests and how your service looks, but alternatively you can always provide the data for all calls with the ID specified (via `-d` or `-D` options). That should basically be equivalent to specifying the ID's in form of a file.
