### ISSUE TITLE
error using makefile

### ISSUE THREAD

**Issue by Arnold1** [bojand/ghz#160]
Hi,

im trying to build the ghz benchmarking binary and run into some issues using the makefile:

**Proto file(s)**
List protocol buffer definitions
none

**Command line arguments / config**
List all command line arguments or config properties
none

**Describe the bug**
```
/bin/bash: -c: line 1: syntax error: unexpected end of file
make: *** [setup] Error 2
```

**To Reproduce**
```
$ git clone https://github.com/bojand/ghz
$ cd  ./ghz
$ make setup
if [ ! -f /bin/tparse ]; then go get github.com/mfridman/tparse; fi;
if [ ! -f /bin/goimports ]; then go get golang.org/x/tools/cmd/goimports; fi;
go: finding golang.org/x/tools latest
if [ ! -f /bin/golangci-lint ]; curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b OME/go/bin v1.21.0
/bin/bash: -c: line 1: syntax error: unexpected end of file
make: *** [setup] Error 2
```

**Expected behavior**
no errors - using make

**Environment**
 - OS: [e.g. macOS 10.14.3]: osx 10.14.6 (18G95)
 - ghz: [e.g. 0.33.0]
 - golang: go version go1.13.7 darwin/amd64 - no GOPATH set

**Screenshots**

**Additional context**

**>>Additional questions<<**
1.) is there a way to use multiple binary data files during the benchmark?
```
ghz --protoset ./bundle.protoset \
  --call helloworld.Greeter.SayHello \
  -B ./hello_request_data.bin \
  0.0.0.0:50051
```

also assume greeter.proto included another proto def (e.g. import "tensor.proto"), how to add them here? - I guess that's the right way:```protoc --proto_path=. --descriptor_set_out=bundle.protoset *.proto```

2.) how can I print the grpc response to stdout?

3.) is there a way to output the serialized binary message which is send when I use "data":{} and define my json for the bundle.protoset?

4.) how can I set a fixed qps for the benchmark e.g. (10qps)

**Comment by bojand** [comment]
Hello, `Makefile` should be working better now.

1) There is no way to use multiple binary files for _input data_. protoset is a format for bundling multiple proto files into a single binary.  
2) This can be achieved using [`--debug`](https://ghz.sh/docs/options#--debug).  
3) This does not really make sense. See answer in 1.  
4) Use [`--qps`](https://ghz.sh/docs/options#-q---qps).
