### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by zhangtiedong0912** [bojand/ghz#162]
**Proto file(s)**
List protocol buffer definitions

**Command line arguments / config**
List all command line arguments or config properties

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment**
 - OS: [e.g. macOS 10.14.3]
 - ghz: [e.g. 0.33.0]
 
**Screenshots**
![image](https://user-images.githubusercontent.com/51616101/74314162-ef710b00-4daf-11ea-8f93-4f226e02bec8.png)

**Additional context**

**Comment by bojand** [comment]
Hello, can you please provide more information with a reproducible example. It seems like the server is unreachable by the ghz test client.

**Comment by mml21** [comment]
Hello,

could this be related to #169, #226 and #184?

**Comment by bojand** [comment]
This issue lacks reproducible details, but i think it may be resolved in [0.80.0](https://github.com/bojand/ghz/releases/tag/v0.80.0)
