### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by bozzwin** [bojand/ghz#169]
**Proto file(s)**
rpc subscribeToResults(ID) returns (stream MatchResult);

**Command line arguments / config**

Command: ghz.exe --config config.json

Config file
{
     "insecure": true,
    "proto": "ProtoFile.proto",
    "call": "package.to.Service.subscribeToResults",
    "data": {
        "ID": "2222"
    },
	"metadata": {
        "trace_id": "{{.RequestNumber}}",
        "timestamp": "{{.TimestampUnix}}"
    },
	"duration": "10m",
    "max-duration": "10m",
    "host": "127.0.0.1:50051"
}

**Environment**
 - OS: [e.g. Windows 10]
 - ghz: [e.g. 0.33.0]
 
**Screenshots**

Summary:
  Count:        200
  Total:        80.03 s
  Slowest:      0 ns
  Fastest:      0 ns
  Average:      20.00 s
  Requests/sec: 2.50

Response time histogram:

Latency distribution:

Status code distribution:
  [DeadlineExceeded]   200 responses

Error distribution:
  [200]   rpc error: code = DeadlineExceeded desc = context deadline exceeded

Could you suggest me how I should test service which return stream?

**Comment by mml21** [comment]
Hi bozzwin,

we have the same issue on our side, see #226.

**Comment by bojand** [comment]
I think this should be addressed with the options introduced in [0.80.0](https://github.com/bojand/ghz/releases/tag/v0.80.0).
