### ISSUE TITLE
Add GHZ into Homebrew package manager

### ISSUE THREAD

**Issue by sergialonsaco** [bojand/ghz#172]
**Is your feature request related to a problem? Please describe.**
In my company, we are using ghz into different projects and different machines, set up them in a manual way is always repetitive and a loss of time, so it would be awesome to have a brew formula to automate the installation of it.

**Describe the solution you'd like**
- To have a brew formula to install ghz, i.e. brew install ghz.
- To update readme with information about how to install it.

**Additional context**
https://brew.sh/

**Comment by bojand** [comment]
Hello, this should be resolved now. You should be able to install using `brew install ghz`.
