### ISSUE TITLE
GHZ web record commands or test settings

### ISSUE THREAD

**Issue by Insutanto** [bojand/ghz#173]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I watch the reports that were recorded a few days ago. I don't remember the parameters that were used in the GHZ command. In one way, It isn't easy to redo the same test after a few days. In another way, It isn't convenient for the user to compare the reports which ware recorded at different times in the same test.

**Describe the solution you'd like**
If GHZ web can record each command's parameters when the reports send to its backend and show the same command's parameters in the frontend so that I can copy those to my terminal and execute it. I don't need to record my parameters by myself and match those with the reports in GZH.

**Describe alternatives you've considered**
If GHZ web can record the config files or commands and support redo's button. It will be excellent that I can redo the test on the website.

**Additional context**
I have written some codes to implement this feature and I am happy to finish it. 😸 
![example](https://user-images.githubusercontent.com/19406290/77985718-c8629e80-7347-11ea-85e0-4d20e1477340.png)

**Comment by bojand** [comment]
Hello, thanks for the suggestion. I am assuming you are ingesting the JSON data [as described](https://ghz.sh/docs/web/api) in the docs. The complete options used for a test are already included in the JSON output and are sent to the ghz-web server and recorded. They are available in the details page if you click on the report link in the table, you should be able to see the details of the run along with the options used.

**Comment by Insutanto** [comment]
I am very sorry for my mistake. I have found my options in the JSON data. Thank you, bojand. you are pretty nice.  👍 
ghz web is more amazing than I was realized.  👍 
In another way, May I help you to improve this function? Maybe we can compare reports of the same options more conveniently and redo it on ghz web. And I am very happy to improve ghz with you. 😸
