### ISSUE TITLE
Passing --config and --call in CLI does not work properly

### ISSUE THREAD

**Issue by Dece** [bojand/ghz#174]
**Proto file(s)**
work-related so can't share, but not related to the issue

**Command line arguments / config**
`./ghz --config config.toml --call my_package.Service/Ping`

**Describe the bug**
Using `--call` in CLI with a config file without a `call` entry results in the following error:
```
ghz: error: Call is required, but blank
```

**To Reproduce**
1. Create a config file with valid entries, but no `call` entry.
2. Execute ghz with `--config <config file>` and `--call <valid call>`

**Expected behavior**
Specifying the call in CLI should be sufficient for ghz to execute successfully, regardless of whether it is present in the config file or not.

**Environment**
 - OS: Debian Stretch
 - ghz: 0.50.0

**Additional context**
If a valid `call` entry is present in the configuration file, using `--call` in CLI properly overrides it.

Let me know if you need further testing, would be happy to help.

**Comment by bojand** [comment]
Hello, thanks for reporting this. I think it should be addressed in [0.51.0](https://github.com/bojand/ghz/releases/tag/v0.51.0).

**Comment by Dece** [comment]
I confirm it works, thank you for the quick fix :+1:
