### ISSUE TITLE
Cannot unmarshal object into Go value using protobuf google wrappers

### ISSUE THREAD

**Issue by haqqi** [bojand/ghz#176]
**Proto file(s)**
```
syntax = "proto3";

package warehouse;

option go_package = "src/proto";

import "entity.proto";
import "google/protobuf/wrappers.proto";

service Owner {
  rpc View (google.protobuf.StringValue) returns (warehouse.OwnerEntity);
}
```

**Command line arguments / config**
```
ghz --insecure --proto ./proto/owner.proto --call warehouse.Owner/View -D ./test.json -O html -o ./report.html localhost:40001
```

test.json

```
{
  "value": "bdccb023-6660-4f1c-99dc-afe9eb52de8f"
}
```

**Describe the bug**

`Error: json: cannot unmarshal object into Go value of type string; Error creating message from data.`

Seems like ghz cannot unmarshal the proto file from included google protobuf wrappers.

**To Reproduce**

Use google protobuf wrappers as parameters

**Additional context**

I have read issue number #48 and it seems using workaround of creating simple message consisting of exactly same variable as google wrappers, does solve the problem. But it is not the root cause, since so many of service will use google wrappers, not only me.

**Comment by bojand** [comment]
Hello I have verified and this should work like so:

```sh
ghz --insecure \
  --proto ./testdata/wrapped.proto \
  --call wrapped.WrappedService.GetMessage \
  -d '"asdf"' \
  0.0.0.0:50051
```

I have added tests and an [example in the docs](https://ghz.sh/docs/examples#wkt).

**Comment by haqqi** [comment]
Thank you for the information. Works well!
