### ISSUE TITLE
ghz-web convert timeunit error

### ISSUE THREAD

**Issue by forestbupt** [bojand/ghz#181]
I believe there is a minor mistake in the function createChartData, it caused the time below 1ms always be displayed as 0, instead of x ns. 

  if (testValue > 1000000) {
    unit = 'ms'
    divr = 1000000
    testValue = testValue / divr
  }

  if (testValue > 1000) {             ######### it should be 1000000000   #########
    unit = 's'
    divr = 1000000000
  }

**Comment by bojand** [comment]
Hello, thanks for reporting this. It should be addressed in [0.54.0](https://github.com/bojand/ghz/releases/tag/v0.54.0). Feel free to reopen if there are issues.
