### ISSUE TITLE
Load Rampup

### ISSUE THREAD

**Issue by juwatanabe** [bojand/ghz#182]
**Is your feature request related to a problem? Please describe.**
Most load tests utilize some kind of rampup/sustained load technique to accurately model user behavior so your service is not being blasted from the start of the test.

**Describe the solution you'd like**
Would it be possible to have a ghz test with stages so I could rampup up from 0 to x concurrency for y duration, then sustain x concurrency for z duration?

**Comment by bojand** [comment]
Hello thanks for the feature.I agree it would be useful feature. This has been somewhat inquired about before (#111), however it is not an insignificant amount of work. I will try and get to it at some point in the future.

**Comment by bojand** [comment]
Hello, I think what's requested here should be available in [0.70.0](https://github.com/bojand/ghz/releases/tag/v0.70.0).
