### ISSUE TITLE
QPS limit not working? And additional question

### ISSUE THREAD

**Issue by BesSlaaneshi** [bojand/ghz#185]
**Command line arguments / config**
ghz --insecure -q 100 -c 5000 -n 5000 --connections=5000 -D ./getQuotes.json -O "html" -o ./output/quotes_auth_5k.html --call grpc.marketdata.MDRequest.GetQuotes --protoset=grpc-marketdata-2.0.249.pb ipaddr:port

**Describe the bug**
i set -q at 100, than start load test.
In html report i see this:
![изображение](https://user-images.githubusercontent.com/40031332/81704877-07bbf900-9477-11ea-8c3b-d811b7e300e5.png)
Requests / sec | 375.46

i expected to see requests / sec at 100 or less, not 375

**Expected behavior**

**Environment**
 - Windows 10 Corporate
 - ghz v0.53.0-beta4

**Additional question**
How did u count avg/min/max when u have errors in channels? like deadlines or unuvailable
i have 2 report with this info:
![изображение](https://user-images.githubusercontent.com/40031332/81705571-dabc1600-9477-11ea-98cb-9439fb911909.png)
both reports - same command line options for ghz

this screenshot means:
left was faster and send more requests per sec, but slowest, fastest and average are higher than right report.
That's totally confuse me.
and the only difference that right report have more errors (deadline and unavailable)
Deadlines didnt count as min/max/avg? because timeout is 20s and report say that slowest was 5.72s
how is this possible

**Comment by lmajercak-wish** [comment]
Im having the same issue, i tried different combinations of configuration but the QPS is always above my configured limit

**Comment by bojand** [comment]
Hello, can you please give [v0.70.0-beta.1](https://github.com/bojand/ghz/releases/tag/v0.70.0-beta.1) pre-release a try. You can find out more info in PR #235. Feel free to provide feedback.

**Comment by bojand** [comment]
Hello, I think what's requested here should be available in [0.70.0](https://github.com/bojand/ghz/releases/tag/v0.70.0).
