### ISSUE TITLE
Get result of each request real-time

### ISSUE THREAD

**Issue by datngohoang** [bojand/ghz#186]
Is there any way to get the result of each request when that request is completed instead of wait for the full report?
Thank you

**Comment by bojand** [comment]
Hello, can you elaborate some more what you mean exactly? Also does "the result of each request" refer to actual response, or actual all stats such as latency and response code? Also some more background and context on what you're trying to do would be helpful. Thanks.

**Comment by vidyabhushan40** [comment]
Hi, is there any way to get response body ? as it is given in jmeter or other tools, without response body its very difficult to check whether the load request is hitting the server or not. Response body will also help to identify the request methods correctly. Please let me know how to get response body.

**Comment by bojand** [comment]
The responses for the calls are serialized in the debug log file when using the [debug option](https://ghz.sh/docs/options#--debug).
