### ISSUE TITLE
Hi, I am trying to perform load testing on my grpc services. But I am unable to import the proto file as I get this error  "organization.proto:1:1: syntax error: unexpected $unk"

### ISSUE THREAD

**Issue by saba71** [bojand/ghz#187]
This is the command I am giving C:\Users\saba.sultan\Desktop\ghz>ghz --proto D:\teo\spectra\protofiles\Protobuf\organization-service\organization.proto --call SpectraSystems.Nimbus.Protos.Organization.Organization.GetAll -d "{\"page_parameters\": [{\"term\":\" \",\"skip\":\"0\",\"top\":\"100\"}]}" organization-service.aks.dev.spectrasoftware.eu
and I get this error
organization.proto:1:1: syntax error: unexpected $unk

This is my proto file

syntax = "proto3";

package SpectraSystems.Nimbus.Protos.Organization;

import "common/common.proto";
import "google/protobuf/empty.proto";

service Organization {

	rpc GetAll (GetAllOrganizationsQuery) returns (GetAllOrganizationsResponse);

	rpc Get (GetOrganizationRequest) returns (OrganizationItem);

	rpc Create (CreateOrUpdateOrganizationCommand) returns (OrganizationItem);

	rpc Update (CreateOrUpdateOrganizationCommand) returns (OrganizationItem);
	
	rpc Delete (DeleteOrganizationCommand) returns (google.protobuf.Empty);
}

message GetAllOrganizationsQuery {
	PageParameters page_parameters = 1; // Required
}

message OrganizationItem {
	string id = 1;
	string name = 2;
	string vat_number = 3;
	repeated TagCategoryDto tag_categories = 4;
}

message GetAllOrganizationsResponse {
	repeated OrganizationItem items = 1;
	PageMeta meta = 2;
}

message GetOrganizationRequest {
	string organization_id = 1; // Required, Guid
}

message CreateOrUpdateOrganizationCommand {

	// Required, Guid
	string id = 1;

	// Required, Length: 1-100
	string name = 2;

	// Optional, Length: 1-100
	string vat_number = 3;

	// Required, Can contain no elements
	repeated TagCategoryDto tag_categories = 4;
}

message DeleteOrganizationCommand {
	string organization_id = 1; // Required, Guid
}

**Comment by saba71** [comment]
I was missing import part to include dependencies

**Comment by atastrophic** [comment]
i am still having this issue, i have dependencies on `google/protobuf/timestamp` `google/api/annotations` as well as other project based proto files. I have tried adding `import-paths` but nothing works. Could you share your fixed command?
