### ISSUE TITLE
Using the `data` field in config file will cause a memory leak.

### ISSUE THREAD

**Issue by elonzh** [bojand/ghz#189]
**Proto file(s)**

see https://github.com/moul/pb/blob/master/grpcbin/grpcbin.proto

**Command line arguments / config**

```toml
insecure = true
import-paths = ["/home/elonzh/workspace/code/pb/grpcbin"]
proto = "grpcbin.proto"
call = "grpcbin.GRPCBin.DummyUnary"
data="""
{
  "f_strings": [
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890",
    "1234567890"
  ]
}
"""
# Number of connections to use. Concurrency is distributed evenly among all the connections. Default is 1.
connections = 3
# Keepalive time duration. Only used if present and above 0.
keepalive = 0
# Number of requests to run. Default is 200.
total = 1000000000
# Number of requests to run concurrently. Total number of requests cannot be smaller than the concurrency level. Default is 50.
concurrency = 200
# Rate limit, in queries per second (QPS). Default is no rate limit.
qps = 0

host = "127.0.0.1:9000"
```

**Describe the bug**

Using the `data` field in config file will cause a memory leak.

PS:  the `data-file` field works fine.

**To Reproduce**

1. start grpcbin server
2. run `ghz --config ./ghz.toml`

make sure you are ready to kill the process.

**Environment**

```text
$ghz -v                 
v0.54.1

$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by bojand** [comment]
Hello,

Can you provide some more details on how are you detecting and observing the memory leak when using `data` vs a data file? Also are you sure the config file is correct (specifically relating to the `data` property)? I think it should be something like:

```toml
insecure = true
import-paths = ["/home/elonzh/workspace/code/pb/grpcbin"]
proto = "grpcbin.proto"
call = "grpcbin.GRPCBin.DummyUnary"
# Number of connections to use. Concurrency is distributed evenly among all the connections. Default is 1.
connections = 3
# Keepalive time duration. Only used if present and above 0.
keepalive = 0
# Number of requests to run. Default is 200.
# total = 1000000000
total = 10000
# Number of requests to run concurrently. Total number of requests cannot be smaller than the concurrency level. Default is 50.
concurrency = 200
# Rate limit, in queries per second (QPS). Default is no rate limit.
qps = 0
host = "127.0.0.1:9000"
[data]
f_strings = [
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890",
  "1234567890"
]
```

Thanks,

**Comment by elonzh** [comment]
@bojand 

Just change the `data-file` property to the `data` property, you will see a significant memory usage when using the `data` property.

Check the screenshots below:

![image](https://user-images.githubusercontent.com/8749411/82516024-59861280-9b4c-11ea-9d02-241df5bd875b.png)

![image](https://user-images.githubusercontent.com/8749411/82516066-73bff080-9b4c-11ea-8eb3-699350cfe899.png)

PS: I killed the process immediately because it eats up my memory so fast ...

**Comment by elonzh** [comment]
I think memory usage should be stable with any total number of requests.

**Comment by bojand** [comment]
There should be better config parsing in [0.55.0](https://github.com/bojand/ghz/releases/tag/v0.55.0) that should error on load and not let you put in such invalid data values at load time, rather than giving errors at test run time.
