### ISSUE TITLE
Add an option to send requests asyncronously

### ISSUE THREAD

**Issue by vlasenkoalexey** [bojand/ghz#209]
As far as I understand from code, currently each worker waits for request to complete before sending a next one regardless of QPS.
If specified worker QPS is higher than QPS the service that is being tested can handle, results start look strange.
In one of my benchmarks, I wanted to test service at 100 QPS, where each request takes ~50 ms to complete.
I expected that I could either setup 1 worker sending 100 QPS or 10 workers sending 10 QPS.
But in order to achieve target 100 QPS I had to set 20 workers 10 QPS each. This is a bit confusing.

It would be nice to have async behavior, where worker is not waiting for request to complete before sending next one at target QPS. Not sure if this is going to work for streaming requests, but for normal requests this makes perfect sense.

**Comment by bojand** [comment]
Hello, I agree there is some quirkiness with the way QPS behaves currently (see #111 and a few other similar issues). I am iterating on improving this and hopefully will have a release in the near future.

**Comment by bojand** [comment]
Hello, I think what's requested here should be available in [0.70.0](https://github.com/bojand/ghz/releases/tag/v0.70.0).
