### ISSUE TITLE
Spaced out low traffic requests

### ISSUE THREAD

**Issue by obvionaoe** [bojand/ghz#211]
Hi, is there a way to space out requests in a given time frame?

I'd like to have a few requests spaced out in a given time frame instead of running all those requests as soon as possible.\
This would be extremely helpful for load testing slow traffic.

Example:
 * Current setup: `100 requests run immediately and stop as the requests finish or if the max duration is reached `
 * Ideal setup: `100 requests run for the entire max duration, but spaced out.`

Thanks

**Comment by bojand** [comment]
I think this can be accomplished using the `--rps` option if you can calculate the constant RPS you desire. For example if you wish to do 100 requests for 20 seconds, that would be 5 requests / second. So just use the `--rps 5` parameter and you should  have approximately evenly spaced out requests.
