### ISSUE TITLE
How to parameterize incoming parameters

### ISSUE THREAD

**Issue by zangyunfei01** [bojand/ghz#214]
When parameters are passed in data, they are fixed values. But it's easy to hit the cache. How do you parameterize the values passed in data so that you can simulate multiple accesses for different requests, rather than multiple accesses for one request

**Comment by bojand** [comment]
Hello, this should be doable using [call template data](https://ghz.sh/docs/calldata), using either UUID or timestamp values to create more dynamic payloads.
