### ISSUE TITLE
Linearly increase qps to find breaking point

### ISSUE THREAD

**Issue by juwatanabe** [bojand/ghz#225]
**Is your feature request related to a problem? Please describe.**
I would like to run a load test that takes a min qps and slowly increases qps every minute until it finds a service's breaking point. 

**Describe the solution you'd like**
For example, say I had:
min qps: 100
increment qps: 10
duration: 10min

My minute by minute example of my test might look like:
0:00 100qps
1:00 110qps
2:00 120qps
3:00 130qps
4:00 140qps
5:00 150qps
6:00 160qps
7:00 170qps
8:00 180qps
9:00 190qps
10:00 end

**Comment by bojand** [comment]
Hello, thanks for the feature request. This type of functionality has been requested in #111 and #182. I have some work-in-progress code for this, just need to finish, test, review, and wrap up everything. My personal time is severely limited at the moment to commit to this project, but I am hoping to return to it and have this done relatively soon when I can as it is a pretty critical improvement.

**Comment by bojand** [comment]
Hello, I think what's requested here should be available in [0.70.0](https://github.com/bojand/ghz/releases/tag/v0.70.0).
