### ISSUE TITLE
Prometheus exposition format output support

### ISSUE THREAD

**Issue by bojand** [bojand/ghz#229]
Similar to the InfluxDB output format we could support [Prometheus exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) for output. This can easily be done manually to print the data in accordance to the format specification; but there is also [expfmt](https://pkg.go.dev/github.com/prometheus/common/expfmt) Go package available although it may be too much overhead to convert data to Prometheus model data for decoding. On the other hand it would be more correct.

**Comment by bojand** [comment]
Initial pass at this has been added to [0.102.0](https://github.com/bojand/ghz/releases/tag/v0.102.0). Please test it out and feel free to create a new issue if there are improvements to be made.

**Comment by m9rco** [comment]
hi @bojand , Is there a grafana panel currently available，Apply to Prometheus
