### ISSUE TITLE
Ramp up Concurrency

### ISSUE THREAD

**Issue by chaganiu** [bojand/ghz#238]
**Is your feature request related to a problem? Please describe.**
It would be nice to ramp up concurrency over a ramp up period that specified by the user.

**Describe the solution you'd like**
I want to be able to specify a ramp up period for concurrency that is evenly distributed over the specified ramp up period.  For example, if I want 500 concurrent requests ramping up over 500 seconds, ghz would start with 1 concurrent requests and would add 1 concurrent request every second until 500 concurrent requests are reached.

I would imagine this scenario would be used only with the duration option.  For example, the parameters of a test might be:

500 concurrent requests, ramped up over 250 seconds (+2/second), for a duration of 30min.

**Describe alternatives you've considered**
I don't think an alternative exists for this scenario in ghz (at least none that I could find).

**Comment by bojand** [comment]
Hello, thanks for creating this issue. Features similar to this has been requested in other issues as well. Recently created PR #235 contains work to allow for such functionality. Please see the notes in the PR for additional documentation and a link to download a pre-release binary. If you can, please test this out and provide feedback in the PR comments. Thanks!

**Comment by chaganiu** [comment]
@bojand I've been using the new beta and it's been working great for me.  thanks for putting that together.

**Comment by bojand** [comment]
Hello, [0.70.0](https://github.com/bojand/ghz/releases/tag/v0.70.0) has been released.
