### ISSUE TITLE
Empty Requests for an rpc aren't working

### ISSUE THREAD

**Issue by shreyakishore** [bojand/ghz#244]
**Proto file(s)**
File name : hotels-services.proto
package com.gonuclei.hotels.v1;

service HotelLanding {
    // RPC to be called to fetch popular destinations
    rpc fetchPopularDestination (HotelEmptyRequest) returns (PopularDestination);
}

message HotelEmptyRequest {}

I tried using ghz for load testing an rpc 'fetchPopularDestination' which actually has an empty request body. I tried sending '' , '{}' , '{""}' , '{"":""}' , [] , {[]} and many other combinations in the request body, none worked. 

command used : ghz --proto hotels-services.proto --call package_name.HotelLanding/fetchPopularDestination -c 1 -n 1 -m 'auth_data' -d '{}' host-address:port

Error distribution:
  [1]   rpc error: code = Unimplemented desc = Method com.gonuclei.hotels.v1.HotelLanding/fetchPopularDestination is unimplemented

How do we send request for an rpc with empty request body?

**Comment by bojand** [comment]
Hello, it seems like your RPC call is not implemented based on the error message, and does not seem to be related to the type. That is it would seem we have serialized the payload properly. Please see [error guide](https://grpc.io/docs/guides/error/) and [status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) documentation. I think I would need more information and a reproducible example. `{}` should work fine with an empty message like the following:

```proto
message EmptyMessage {}
```

As well `{}` should work with [`google.protobuf.Empty`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty) type. 

Here is an example call working using https://grpcb.in/

```
ghz --insecure \
  --proto ./testdata/grpcbin.proto \
  --call grpcbin.GRPCBin.Empty \
  -d '{}' -c 2 -n 10 \
  grpcb.in:9000

Summary:
  Count:	10
  Total:	1.21 s
  Slowest:	688.46 ms
  Fastest:	127.68 ms
  Average:	241.75 ms
  Requests/sec:	8.25

Response time histogram:
  127.679 [1]	|∎∎∎∎∎∎
  183.758 [7]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  239.836 [0]	|
  295.914 [0]	|
  351.993 [0]	|
  408.071 [0]	|
  464.149 [0]	|
  520.228 [0]	|
  576.306 [0]	|
  632.385 [0]	|
  688.463 [2]	|∎∎∎∎∎∎∎∎∎∎∎

Latency distribution:
  10 % in 127.68 ms
  25 % in 128.61 ms
  50 % in 129.77 ms
  75 % in 133.45 ms
  90 % in 688.46 ms
  95 % in 688.46 ms
  99 % in 688.46 ms

Status code distribution:
  [OK]   10 responses
```
