### ISSUE TITLE
Avg Response Time for Successful Requests

### ISSUE THREAD

**Issue by chaganiu** [bojand/ghz#248]
**Is your feature request related to a problem? Please describe.**
I'm testing a service that has a large number of failed requests due to as-designed load shedding.  I'm wondering if there is a way to see the avg response time for just the successful requests.  Maybe this is already in the report and I'm just not reading it correctly.  Here is what one of my reports looks like:

![image](https://user-images.githubusercontent.com/71658081/101372868-551c0f80-387a-11eb-87b6-193d437d882a.png)

**Describe the solution you'd like**
Something that shows the avg response time for successful requests

**Comment by bojand** [comment]
Hello, the actual stats for fastest, slowest, average, histogram, and latency distributions only take into account the responses with OK status. So the erroneous / failed responses are collected and counted towards the total, RPS, and calculating the percentages of various statuses, but the stats are only based on successful / OK responses. 

I agree the histogram labels do not appear 100 % correct, as the labels should add up to the OK status count. I have confirmed this works with a simple hello world app by introducing randomized errors in response, and the HTML report was correct. What version are you using? Hmm can you somehow provide a reproducible example?
