### ISSUE TITLE
How to send mixed requests containing binary data?

### ISSUE THREAD

**Issue by asarkar** [bojand/ghz#252]
**Proto file(s)**
```
rpc Ask(stream AudioStreamRequest) returns (stream AudioStreamResponse) {}

message AudioStreamRequest {
    bytes audio = 1;
    AudioMetadata meta = 2;
}
```

The documentation describes sending text and binary data, but not how to send mixed requests containing binary data. Given the proto above, there's an audio file that needs to be streamed, whereas `meta` is a textual message.

**Comment by bojand** [comment]
Hello this should be possible in [0.80.0](https://github.com/bojand/ghz/releases/tag/v0.80.0) using the new Data Provider API. For example something like (just coding freehand):

```go
// ... create the test stream data
streamProtoData := []*audioprotopackage. AudioStreamRequest{
	&audioprotopackage. AudioStreamRequest{Bytes:..., Meta: ...}, // stream message 1
	&audioprotopackage. AudioStreamRequest{Bytes:..., Meta: ...}, // stream message 2
}

streamDynamicData := make([]*dynamic.Message, 0, len(streamProtoData))

for i, msg := range streamProtoData {
	dynamicMessage, err := dynamic.AsDynamicMessage(protoMessage)
	if err == nil {
		streamDynamicData = append(streamDynamicData, dynamicMessage)
	}
}

// elsewhere where you setup the run
WithDataProvider(func(*CallData) ([]*dynamic.Message, error) {
	return streamDynamicData, nil
}),
```

In future release we hope to remove reliance on the `github.com/jhump/protoreflect/dynamic package` for these APIs and use proto message interfaces.

**Comment by asarkar** [comment]
Your code seems to be in Go, what about other languages (Java)?

**Comment by bojand** [comment]
This is a Go package, so only Go would work.

For CLI options you should be able to use the `-B` (binary) option. Simply [serialize the whole](https://developers.google.com/protocol-buffers/docs/gotutorial#writing-a-message) message to a binary file first. Then use the file with `-B ./my_message.bin` for example. This is usually more practical when having to deal with some of the message having binary data.

Alternatively you can try and input the request as JSON data but [use base64 string](https://developers.google.com/protocol-buffers/docs/proto3#json) representation of the image as the value for the `audio ` field.
