### ISSUE TITLE
Template to create randomNumber within some range

### ISSUE THREAD

**Issue by Jaydev13** [bojand/ghz#260]
**Is your feature request related to a problem? Please describe.**
Service currently accepts request where a field is a number and in a range(1 to N). While Sending million request the field is exceeding the given range.

**Describe the solution you'd like**
Create a randomNumber template which accepts range or at least and end number. 

**Describe alternatives you've considered**

**Additional context**

**Comment by bojand** [comment]
Hello, can you please elaborate and add some details on the proto, RPC and how data is seeded. I am missing something I think. Seems like you may have an RPC like:

```proto
rpc SomeAction(SomeRequest) returns (SomeResponse) {}

message SomeRequest {
    int64 some_number = 1;
}
```

How are you actually seeding this? There is `RequestNumber` field in the call template data that you can use, which should suffice since it's an `int64` with a max of `9223372036854775807`...

**Comment by Jaydev13** [comment]
Hi,
Currently I am using RequestNumber Template Data but that is not something which is needed.
I have stated the reason for not using the RequestNumber field. 
There is an RPC service which has a check on the incoming number on a field.
rpc SomeAction(SomeRequest) returns (SomeResponse) {}

message SomeRequest {
    int64 some_number = 1; // There is code to verify that the some_number is less than 500.Else error response is sent.
}

Currently if I seed this some_number with RequestNumber then only 500 requests gets successful response. since any number above 500 responds with error response.

If there is a template by which we can generate any random number between 1 to 500 in each request. Then for each request the number will not be above 500 and the response will not be error response.

Similar to the template Data for randomString with length. randomNumber with length is what is needed for this.
