### ISSUE TITLE
How to run multiple GRPC endpoints parallelly and aggregate reports

### ISSUE THREAD

**Issue by Siddharthk** [bojand/ghz#264]
My use case is to run around 50 parallel GRPC endpoints and then aggregate the reports for those endpoints. I am not able to find this info in the docs. Is this doable?

Example aggregated report of Jmeter:
![image](https://user-images.githubusercontent.com/718854/111060418-baf3e500-84c2-11eb-9b98-aea9afc6962a.png)

**Comment by bojand** [comment]
I think this should be doable programmatically using the Go package, and run the tests concurrently. It is not something possible with the CLI.
