### ISSUE TITLE
Is it any documentation how to use GHZ with TensorFlow Serving?

### ISSUE THREAD

**Issue by groj** [bojand/ghz#266]
Hi, TensorFlow Serving (TFS) is open source solution used as inference service (in machine learning field). TFS can base on gRPC protocol to communicate with downstream client applications. So I guess I should be possible to apply GHZ for creating and sending  requests into TFS server. Have you tried it or do you have such plans?

**Comment by bojand** [comment]
Hello, I am not familiar with TensorFlow Serving. If the server exposes a gRPC service, and you have access to the protocol definition, I think you should be able to run ghz tests against it.

**Comment by salliewalecka** [comment]
This setup is assuming you are running the tfserving docker container locally and the input is variable called text which is a 1x1 string tensor. 

- Clone the TF serving docs https://github.com/tensorflow/serving/tree/master/tensorflow_serving
- `cd serving` 

```
~/ghz --insecure --proto tensorflow_serving/apis/prediction_service.proto  \
--call tensorflow.serving.PredictionService/Predict \
-d '{"model_spec":{"name": "you-model-name", "signature_name":"your-function"},"inputs":{"text":{"dtype": 7,"tensor_shape": {"dim":[{"size": 1},{"size": 1}]}, "string_val":["some-base-64-encoded-str"]}}}' \
127.0.0.1:8500
