### ISSUE TITLE
Question: Is support for custom template functions on metadata dropped? 

### ISSUE THREAD

**Issue by tyrone-anz** [bojand/ghz#271]
I am using custom template functions to give dynamic header data on each request. But I've noticed on the latest version that it is no longer supported. 

Data Provider (`funcs` used)
https://github.com/bojand/ghz/blob/532fb1e6211266eced3e4fe6454df6d907e4a052/runner/requester.go#L128

Metadata Provider (`funcs` not used)
https://github.com/bojand/ghz/blob/532fb1e6211266eced3e4fe6454df6d907e4a052/runner/requester.go#L138

Initialised `callData` with nil
https://github.com/bojand/ghz/blob/532fb1e6211266eced3e4fe6454df6d907e4a052/runner/data.go#L223

Is this correct? If so, is this intentional?

I am currently using `v0.70.1-0.20201201022711-15f8ed97a55a`

**Comment by bojand** [comment]
Hmm I think this seems like a bug... will try and fix soon.

**Comment by bojand** [comment]
Hello, I think this should be fixed in [0.95.0](https://github.com/bojand/ghz/releases/tag/v0.95.0).

**Comment by tyrone-anz** [comment]
Working as expected @bojand. Thank you for adding it back so quickly.
