### ISSUE TITLE
Is there support for benchmarking Unix Domain Socket? 

### ISSUE THREAD

**Issue by mymddoan** [bojand/ghz#292]
Is there support for benchmarking Unix Domain Socket? I'm interested to see if there's a performance increase between using UDS vs TCP for local connection.

**Comment by bojand** [comment]
I believe this should be supported as it's [supported by grpc-go](https://github.com/grpc/grpc/blob/master/doc/naming.md), although I have not tried it.

**Comment by BogdanIonesq** [comment]
I just tested this scenario and it does work. If I have a gRPC application listening on a unix domain socket at `/tmp/example.sock`, the following command successfully benchmarks the endpoint:
```
ghz --insecure --proto ./greeter.proto --call helloworld.Greeter.SayHello -d '{"name":"Joe"}' unix:///tmp/example.sock
```

**Comment by nminkov** [comment]
I know is old question, but here is an example https://github.com/Danie1/grpc/tree/example-helloworld-uds/examples/cpp/helloworld_uds
