### ISSUE TITLE
Support for gRPC with XDS

### ISSUE THREAD

**Issue by stevenctl** [bojand/ghz#293]
**Is your feature request related to a problem? Please describe.**

Testing with XDS resolver enabled would be very useful, especially when trying to compare:
* Plain gRPC
* gRPC with some proxy in front of it (e.g. Envoy, Linkerd proxy, etc)
* gRPC with XDS resolver enabled/TLS configs etc.

**Describe the solution you'd like**

Simply performing the side-effect import will allow `xds:///` scheme to be used (assuming the user has the proper env variables for GRPC_XDS_BOOTSTRAP) set. 

**Additional context**

gRPC has added support for configuration via XDS: https://github.com/grpc/proposal/blob/master/A27-xds-global-load-balancing.md

To use it as a client in Go, we simply need to add the following side-effect import:

```go
// To install the xds resolvers and balancers. 
_ "google.golang.org/grpc/xds"
```

This just registers the builder, but doesn't do anything unless a bootstrap file is provided.

**Comment by bojand** [comment]
Hello I think this is addressed via #300 and should be available in [0.100.0](https://github.com/bojand/ghz/releases/tag/v0.100.0). Feel free to reopen the issue if there are problems.
