### ISSUE TITLE
[Feature Request] Add Alpine runtime to compiled images

### ISSUE THREAD

**Issue by timothyclarke** [bojand/ghz#307]
**Is your feature request related to a problem? Please describe.**
This is not a problem
We use docker container with alpine linux (where possible) and would like to use an alpine (musl) build rather than glibc.
I would like that build added to the releases rather than replacing an exiting one

**Describe the solution you'd like**
The releases page includes `ghz-alpine-linux-x86_64.tar.gz`which is compiled on musl based linux

**Describe alternatives you've considered**
Switching parts of our build tooling to debian / glibc based images (currently implemented this, but would prefer alpine).

**Comment by bojand** [comment]
Hello, can you elaborate some more on the specific problem you are encountering. `ghz` is _not_ built with `CGO_ENABLED`, so it should be a completely self contained Go-sourced static binary. Unless I am missing something, I think musl vs. glibc does not apply to `ghz` binary specifically. `ghz-web` is built with `CGO_ENABLED` due to sqlite use.

**Comment by timothyclarke** [comment]
When I try running it in alpine it gives a file not found error as it's trying to load `/lib64/ld-linux-x86-64.so.2`

**Comment by fenollp** [comment]
```shell
alias we='wget --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36" '
we https://github.com/bojand/ghz/releases/download/v0.105.0/ghz-linux-x86_64.tar.gz
# ...
tar xvf ghz-linux-x86_64.tar.gz 
# ...
file ghz
ghz: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=3rlWETmaPMfbN6sQvmZk/O2gZF4jvIr1fGT5kwLXk/knQ5R8IoUD3dSqPMONfe/E5guC32jep9UcWkZiD2Z, stripped
# Note: *dynamically linked*
```
I've noticed this as well when trying to use the static distroless image on PR https://github.com/bojand/ghz/pull/333.

Note locally building is fine:
```shell
make build
# ...
file dist/ghz
dist/ghz: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Lj2WDIMpLYz_zMs4KLP9/EiqEkIWBofoaIKF-MBDn/u3iz3hTvDJEdeNOCxzzv/Oj5R-1cZcomUh4qjvUpE, stripped
# Note: *statically linked*
```
