### ISSUE TITLE
Won't call to microservice built using go-micro framework

### ISSUE THREAD

**Issue by comtom** [bojand/ghz#32]
I have a service running locally, registered in consul (which I use as service registry):

```
    2018/10/08 16:31:29 [DEBUG] http: Request PUT /v1/agent/check/pass/service:enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549?note= (299.368µs) from=127.0.0.1:34708
    2018/10/08 16:31:38 [DEBUG] agent: Skipping remote check "serfHealth" since it is managed automatically
    2018/10/08 16:31:38 [DEBUG] agent: Service "enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549" in sync
    2018/10/08 16:31:38 [DEBUG] agent: Check "service:enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549" in sync
```

I tried to run latest pre-built version of ghz downloaded from the download page and then ran:

```
$ ./ghz -proto="/home/comtom/Projects/src/github.com/TodayTix/ttproto-provider-interface/proto/ProviderService/ProviderService.proto" -call="enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549.GenerateShows" -d="{}" 127.0.0.1:34708 -insecure 

but failed with: **cannot find service "service:enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549"**
```

also tried service:enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549.GenerateShows as service name and just enta-nimax. the same happened. What I'm doing wrong?

**Comment by bojand** [comment]
Hello, thanks for reporting this. I'll have to investigate further once I get a little bit of time. Can you check does [grpcurl](https://github.com/fullstorydev/grpcurl) work correctly if you call it similarly. Something like:

```sh
grpcurl -insecure -d '{}'  127.0.0.1:34708 enta-nimax-b51023cb-cb2f-11e8-b79b-a08cfd74f549.GenerateShows
```

**Comment by comtom** [comment]
`./grpcurl -plaintext  -d '{}'  localhost:35929 enta-nimax-c83aee60-cbc9-11e8-91c6-a08cfd74f549.GenerateShows
Error invoking method "enta-nimax-c83aee60-cbc9-11e8-91c6-a08cfd74f549.GenerateShows": failed to query for service descriptor "enta-nimax-c83aee60-cbc9-11e8-91c6-a08cfd74f549": server does not support the reflection API`

it seems to start the connection but I got that error. Also found that is using http/2 without TLS

**Comment by nzoschke** [comment]
I'm not familiar with go-micro, but I am familiar with the `server does not support the reflection API` error message from `grpcurl`.

With `google.golang.org/grpc` you need to add server reflection.

Here's an example on one of my services:

https://github.com/nzoschke/omgrpc/pull/7/commits/07b3fb4e56d3464a52f8bc21d2925072d401adfd

And here is the reflection package for reference:

https://github.com/grpc/grpc-go/tree/master/reflection
