### ISSUE TITLE
Add reflection support

### ISSUE THREAD

**Issue by bojand** [bojand/ghz#35]
Instead of specify the proto file we could use reflection to build the client for making the requests. The user would still have to provide the call details that has to correctly match the reflection results. Reflection is only supported [by a subset of languages](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md).

**Comment by jayhuang75** [comment]
Any update on this. Much appreciated this good tools.

**Comment by bojand** [comment]
Hello, Hoping to get to this relatively soon-ish, but depending on the level of effort needed (unknown to me right now) it may take some time to implement properly.

**Comment by srenatus** [comment]
[`grpcurl`](https://github.com/fullstorydev/grpcurl) and [`grpcui`](https://github.com/fullstorydev/grpcui/) could serve as examples here, with their use of [`protoreflect`](https://github.com/jhump/protoreflect).

**Comment by bojand** [comment]
Hello this should be implemented now in [v0.30.0](https://github.com/bojand/ghz/releases/tag/v0.30.0) and seems to be working from my local (albeit limited) testing. Please feel free to create new issues if you encounter any problems with the feature.

**Comment by srenatus** [comment]
Very nice. Works like a charm. Thank you! 😃
