### ISSUE TITLE
Metadata not being passed to reflection endpoint

### ISSUE THREAD

**Issue by thieman** [bojand/ghz#367]
**Proto file(s)**
Don't think it's relevant, using reflection and not getting far enough to get a response anyway

**Command line arguments / config**
`ghz -m '{"authorization":"Bearer my-token"}' --call my-endpoint -d '{"key": 2}' --insecure localhost:2300`

**Describe the bug**
I'm trying to pass an `authorization` header using metadata. This should generally work, it works in my Python gRPC client and it worked for this person a few years ago using ghz: https://github.com/bojand/ghz/issues/120

However, my server keeps returning an error indicating no `authorization` header was received at all. I'm not sure how to verify what's being sent from `ghz`'s perspective, I didn't see a verbose mode. Is there a debug log I can activate somehow?

**To Reproduce**
1. Try to pass some metadata using ghz
2. Metadata is not received by the server

**Expected behavior**
1. Try to pass some metadata using ghz
2. Metadata is received by the server

**Environment**
 - OS: macOS 12.4
 - ghz: 0.109.0 installed from brew

**Comment by thieman** [comment]
Ah, here's the debug log:

```
{"level":"debug","time":"2022-06-23T14:54:37.128062-04:00","message":"Start Run","config":{"proto":"","protoset":"","call":"GetServiceAccounts","cacert":"","cert":"","key":"","count-errors":false,"skipTLS":false,"skipFirst":0,"cname":"","authority":"","insecure":true,"total":200,"concurrency":50,"concurrency-schedule":"const","concurrency-start":0,"concurrency-end":0,"concurrency-step":1,"concurrency-step-duration":"0s","concurrency-max-duration":"0s","connections":1,"rps":0,"duration":"0s","duration-stop":"close","max-duration":"0s","timeout":"20s","data":{"key":2},"data-file":"","binary-file":"","metadata":{"authorization":"Bearer my-token"},"metadata-file":"","stream-interval":"0s","stream-call-duration":"0s","stream-call-count":0,"stream-dynamic-messages":false,"output":"","format":"summary","connect-timeout":"10s","keepalive":"0s","cpus":8,"debug":"/tmp/debug.log","host":"localhost:2300","load-schedule":"const","load-start":0,"load-end":0,"load-step":0,"load-step-duration":"0s","load-max-duration":"0s","lb-strategy":"","max-recv-message-size":"","max-send-message-size":""}}
{"level":"debug","time":"2022-06-23T14:54:37.129035-04:00","message":"Creating client connection","options":[{},{}]}
{"level":"error","time":"2022-06-23T14:54:37.201025-04:00","message":"Error from run: rpc error: code = Unauthenticated desc = authentication must be provided","stacktrace":"main.main\n\t./main.go:329\nruntime.main\n\truntime/proc.go:250"}
```

**Comment by thieman** [comment]
I was able to figure this out, I think what's happening is `ghz` isn't passing the metadata on the call to the reflection endpoint. Since my reflection endpoint requires authentication, that makes it unusable. I was able to work around by passing in a `.proto` file explicitly, but this still smells like a bug to me.

**Comment by bojand** [comment]
Would [`--reflect-metadata`](https://ghz.sh/docs/options#--reflect-metadata) option help in this case? It's metadata passed in as stringified JSON used only for reflection request.

**Comment by thieman** [comment]
Certainly would! I'd missed that, thanks.
