### ISSUE TITLE
About the recent releases

### ISSUE THREAD

**Issue by chenrui333** [bojand/ghz#389]
👋 it looks like the most releases are marked with `0.112.0-pre.0` and `v0.112.0-pre.1`, are they stable releases or should be marked as `pre release`? Thanks!

![image](https://user-images.githubusercontent.com/1580956/210199223-382dc786-f87c-4633-a811-3c77d0dda251.png)

Also relates to https://github.com/Homebrew/homebrew-core/pull/119551

**Comment by bojand** [comment]
Hello, in terms of `ghz` too itselkf, this release should be unchanged from 0.111.0. 
Mostly includes small dependency updates to `ghz-web` and adds arm build. It's a prerelease as I wanted to test the arm builds in GitHub Actions.
You can see the changelog in [v0.112.0-pre.0 release notes](https://github.com/bojand/ghz/releases/tag/v0.112.0-pre.0).
Hope this helps.

**Comment by chenrui333** [comment]
Got you, thanks!
