### ISSUE TITLE
why the gRPC connect not closed in server side

### ISSUE THREAD

**Issue by thincal** [bojand/ghz#39]
When using this great tool to make 2K concurrent request, I find that the sock connection is still kept open:

```
# lsof -p 102372 | grep -c "sock"
1394
```
After double checked the code in this tool, it seems that the `close` should be called.

Do you know is this a optimized design in gRPC that to keep a connection pool on demand ? or something else wrong.

**Comment by thincal** [comment]
it's strange that if the response could be returned quickly less than 1 second, the sock handle won't be increased, but if the response takes more time than 1-10 seconds, the sock handle will be increased and won't be closed even after the connection closed.

It sounds very strange.

**Comment by thincal** [comment]
It sounds like that when the connection pool bursted for massive requests, but grpc doesn't shrink back to normal after the request is done.

**Comment by bojand** [comment]
Hello, can you provide some more information on reproducible steps to demonstrate the issue. 
Thanks.
