### ISSUE TITLE
received the unexpected content-type "text/plain"

### ISSUE THREAD

**Issue by seaguest** [bojand/ghz#40]
Hello,

I am using go-micro to develop my micro service and I use consul as service registry (it listens on 8500).

I tried:
```
ghz -proto ./hello.proto -insecure -call hello.Hello.Hi -d '{"name": "Joe"}' 127.0.0.1:8500
```
it said 
```
Latency distribution:
Status code distribution:
Error distribution:
  [143]	rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
  [57]	rpc error: code = Unavailable desc = transport is closing
```

If I change 8500 to the port on which service listens, I got

```
Latency distribution:
Status code distribution:
Error distribution:
  [200]	rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain"
```

Here are two questions:
1, why this error happens "received the unexpected content-type "text/plain""?
2, how to make it work with consul?

**Comment by bojand** [comment]
Hello, can you make any successful requests to either the consul or directly to the service itself using a test client application? What about using [gurpcurl](https://github.com/fullstorydev/grpcurl)? I am away for a week with limited time so probably can't dig deeper into this until start of December; but will investigate then. Good luck and let me if you find the resolution.

**Comment by bojand** [comment]
Thanks for checking this. Then it likely means there is an issue somewhere else in the setup. It's most likely not an issue with ghz or grpcurl. Can you make a test client application using the gRPC generated client and do some test calls please, so we can see what that results in.

**Comment by seaguest** [comment]
I verified the problem come from the go-micro framework which doesn't support standard rpc call.
I switched to standard grpc, then grpcurl and ghz both work.
