### ISSUE TITLE
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"

### ISSUE THREAD

**Issue by gxiaoying** [bojand/ghz#43]
When I using this great tool to test my service I got a rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake".

My service works well:
#docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                      NAMES
8ecd78ab381d        test:my-test   "/bin/sh -c 'python …"   32 minutes ago      Up 32 minutes       0.0.0.0:50051->50051/tcp   sad_goodall

And the command I used:
./ghz -proto ../api/grpc/test_service.proto -call mytest.TEST.evaluate -c 5 -n 15 -D ./input.json -o ./test_result.html -O html -name emacs-load-testing localhost:50051

**Comment by gxiaoying** [comment]
Sorry, I fix this error. It works now.

**Comment by nlohmann** [comment]
I am experiencing the same issue. What did you do to fix it?

**Comment by gxiaoying** [comment]
I added option "-insecure" in the command line and it worked.

**Comment by nlohmann** [comment]
Ok. I tried that, too. It turned out, it should be given before the hostname, because it seems to be ignored otherwise. Thanks for the quick response!
