### ISSUE TITLE
When metadata is "preseeded" (constant per request),  ghz adds repeated `grpc-accept-encoding=gzip` headers

### ISSUE THREAD

**Issue by TheSafo** [bojand/ghz#441]
**Describe the bug**
When metadata is "preseeded" (constant per request),  ghz adds repeated `grpc-accept-encoding=gzip` headers (each request keeps appending to the same object so it's duplicated 1000s of times).

**To Reproduce**
`ghz--metadata='{"my-header":"my-value"}' --call <request>  -B <data> <url> --enable-compression`

**Expected behavior**
`grpc-accept-encoding=gzip` is set a single time on the metadata.

**Environment**
 - OS: 
 - ghz: v0.118.0
 
**Additional context**
I believe this https://github.com/bojand/ghz/blob/master/runner/worker.go#L99-L101 is the problematic line - when the MD object is shared accross all requests it infinitely appends to the same object.

**Comment by bojand** [comment]
Oof. I think this should be fixed with #444 and available in [0.120.0](https://github.com/bojand/ghz/releases/tag/v0.120.0). Feel free to reopen with more info if this doesn't fix it.
