### ISSUE TITLE
Multiple connection and not persistent connection scenes

### ISSUE THREAD

**Issue by xysLion** [bojand/ghz#50]
Hi there,
While trying to load test my server using ghz, I want to call it use multiple connection or not persistent connection scenes, it will support in the future.

**Comment by bojand** [comment]
Hello, can you elaborate some further on what exactly your usage is and what you would like to test. 

Right now we create 1 connection then concurrently make requests in goroutines to the server based on the parameters specified (specifically `-c`).

To do multiple connections might be a little complicated. The somewhat simpler and more practical approach could be to provide a a couple of options:
1. Open a new connection for each goroutine worker. So `-c` number of connections. Close connection when worker is done. This may make more sense to simulate some real world scenarios.
2. Open a connection for each request and close it at the end. To me this feels impractical as it is not  how gRPC would be really used in real world.

Opinions?

**Comment by DevikaNuclei** [comment]
Based on the first option you provided, I am trying to simulate such a real time scenario with multiple connections in your tool. Was thinking on lines of changing the requester struct to support multiple connections. is there any simpler approach to this?

**Comment by bojand** [comment]
Hello,

Thanks for the comment. I somewhat forgot about this, but I understand the issue. I will think about practical and elegant approach to this and hope to have something soon.

**Comment by bojand** [comment]
Hello, please review the proposed changes to allow multiple connections in #85.

**Comment by bojand** [comment]
This should be supported in [0.35.0](https://github.com/bojand/ghz/releases/tag/v0.35.0). Feel free to open a new issue if you find any problems.
