### ISSUE TITLE
Failed to load imports for "sr.proto". Syntax error: unexpected $unk

### ISSUE THREAD

**Issue by BesSlaaneshi** [bojand/ghz#52]
i have config_test.json:
```
{
	"proto": "C:/Users/1/Desktop/GHZ/protorepo/sr.proto",
	"call": "grpc.refe.SR.GEInfo",
	"host": "localhost:30058",
	"c": 2,
	"n": 4,
	"x": "1s",
	"o": "C:/Users/1/Desktop/GHZ/output",
	"O": "html",
	"insecure": true,
	"i": [
		"C:/Users/1/Desktop/GHZ/protorepo/grpc-proto/src/"
	]
}
```
my sr.proto looks like:

```
syntax = "proto3";

package grpc.refe;

import "proto/common/e.proto";
import "proto/common/si.proto";
import "google/protobuf/empty.proto";

option java_multiple_files = true;
option objc_class_prefix = "ABC";

message EResponse {
    repeated proto.common.E         e = 1;
}

service SR {
rpc GEInfo(google.protobuf.Empty) returns (EResponse) {}
}
```
my e.proto looks like
```
syntax = "proto3";

package proto.common;

option java_multiple_files = true;
option objc_class_prefix = "ABC";

message E {
int32 id = 1;
string name = 2;
}
```
my si.proto looks like:
```
syntax = "proto3";

package proto.common;

option java_multiple_files = true;
option objc_class_prefix = "ABC";
```

i start ghz with `ghz -config .\config_test.json`
and get error:
`failed to load imports for "sr.proto": proto/common/si.proto:1:1: syntax error: unexpected $unk`

all files for import located: C:\Users\1\Desktop\GHZ\protorepo\grpc-proto\src\proto\common

i cant understand what this error means and how to fix it.
for this method i need only e.proto and empty.proto,
but i have another methods that need si.proto
For now i dont know what to do and need help.

using ghz v 0.22.0 on Windows

**Comment by bojand** [comment]
Hello, unfortunately I do no have Windows or easy access to test on that platform so can't really reproduce if there is an issue related to usage of that OS specifically. However a few things:

```proto
message E {
  in32 id = 1;
  string name = 2;
}
```
There is a typo there. Type of `id` should be `int32` instead of `in32`

The config file specifies the `proto` as

`C:/Users/1/Desktop/GHZ/protorepo/sr.proto`

But you say all proto files are in ` C:\Users\1\Desktop\GHZ\protorepo\grpc-proto\src\proto\common` while the imports are `"proto/common...` and `i` is `"C:/Users/1/Desktop/GHZ/protorepo/grpc-proto/src/"`. This all is somewhat contradictory and confusing...

Based on the main `sr.proto` file is at `C:/Users/1/Desktop/GHZ/protorepo/sr.proto` and the contents of it it seems you should have something like:

```
sr.proto
|-- proto/common/
     |-- e.proto
     |-- si.proto
```

We will automatically add the proto file path's directory in import paths, your import paths should just include the location of `empty.proto` which should be wherever `protoc` is installed.

Finally, you include `si.proto` but that proto file doesn't define any messages or calls, so it seems completely redundant.

Hope all of this helps.

**Comment by BesSlaaneshi** [comment]
sorry, i updated first message to fix typo.
i deleted some info from proto files because they are big.
si.proto - have messages, i just delete them while write this issue because GEinfo dont need the file si.proto and the problem not in message.
but another messages in sr.proto - need it. (i just didnt write it here)
at least the problem is exactly with si.proto referee to error text message.

and import are correctly. i have content somethink like this:
sr.porot
|-- protorepo
    |-- sr.proto
    |-- grpc-proto
        |-- src
            |-- proto
                 |-- common
                      |-- e.proto
                      |-- empty.proto
                      |-- si.proto

also e.proto is correctly imported with no error. because the error exactly in si.proto
and with "i" no problem because ghz find proto files correctly. Just protoc gives error that means that he cant parse si.proto. or i dont know -_-
for the test i add "syntax error" in e.proto in line 3 symbol 5
and when i start ghz - `i get error failed to load imports for "sr.proto": proto/common/e.proto:3:5: syntax error`
also error means si.proto:1:1:  -  that's means first line first symbol?

also we try this on linux, but the problem are same.
and our programmers can compile proto files with no errors in protoc. They are correct and work good.

**Comment by bojand** [comment]
Hello, it would be very useful if you could provide a full reproducible example with all the code for all relevant proto files and the structure of folder and `ghz` parameters. You can just place dummy / simple, but valid messages, that's similar to your usage. I am having a hard time under standing the structure and relationship of all the protos from all the information above.

**Comment by BesSlaaneshi** [comment]
Hello. I make example files for you to reproduce my error.
So, i start ghz with command `ghz -config .\configtestsr.json`
And get error.
`failed to load imports for "sr.proto": proto/common/si.proto:1:1: syntax error: unexpected $unk`

[GHZtest.zip](https://github.com/bojand/ghz/files/2807728/GHZtest.zip)

**Comment by BesSlaaneshi** [comment]
Also. It worked with protoset.
But still can't make it with path to .proto

**Comment by bojand** [comment]
Hello, thanks for including the data. Sorry I have not had the time to look into this deeper, but will try to do so soon. Protoset is certainly an option as a workaround if that works for you.

**Comment by bojand** [comment]
There seems to be [`U+FEFF`](https://en.wikipedia.org/wiki/Byte_order_mark), which can be [problematic it seems](https://medium.freecodecamp.org/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7), at the start of the file. Removing it fixes the problem
```
$ bat /Users/bojand/Downloads/GHZtest/grpc-proto/src/proto/common/si.proto
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /Users/bojand/Downloads/GHZtest/grpc-proto/src/proto/common/si.proto
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ <U+FEFF>syntax = "proto3";
   2   │
   3   │ package proto.common;
   4   │
   5   │ option java_multiple_files = true;
   6   │ option objc_class_prefix = "AAA";
   7   │
   8   │
   9   │ message SI {
  10   │     message TAndM {
  11   │         string t = 1;
  12   │         string m = 2;
  13   │     }
  14   │
  15   │     oneof spec {
  16   │         int64               secur_id             = 1;
  17   │         TAndM                   t_m                      = 2;
  18   │     }
  19   │ }
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by LoremipsumXu** [comment]
In Windows OS,try using dos2unix to convert to proto file,it works for me!
