### ISSUE TITLE
InfluxDB line protocol is invalid

### ISSUE THREAD

**Issue by minddazed** [bojand/ghz#54]
The ghz output documentation provides samples of influxdb-details output. However this is not valid line protocol. If I try to copy-paste one of the influxdb-details examples into a POST, I get the following error:

Request:
POST /write?db=ghz HTTP/1.1
Host: localhost:8086
Content-Type: application/x-www-form-urlencoded
ghz_detail,proto="/testdata/greeter.proto",call="helloworld.Greeter.SayHello",host="0.0.0.0:50051",n=1000,c=50,qps=0,z=0,timeout=20,dial_timeout=10,keepalive=0,data="{\"name\":\"{{.InputName}}\"}",metadata="{\"rn\":\"{{.RequestNumber}}\"}",hasError=false latency=5157328,error=,status=OK 681023506

Response:
{
    "error": "unable to parse 'ghz_detail,proto=\"/testdata/greeter.proto\",call=\"helloworld.Greeter.SayHello\",host=\"0.0.0.0:50051\",n=1000,c=50,qps=0,z=0,timeout=20,dial_timeout=10,keepalive=0,data=\"{\\\"name\\\":\\\"{{.InputName}}\\\"}\",metadata=\"{\\\"rn\\\":\\\"{{.RequestNumber}}\\\"}\",hasError=false latency=5157328,error=,status=OK 681023506': missing field value"
}

There are two problems with the request, specifically the last two field values:
1) Line protocol does not allow sending nulls, so "error=" is an invalid input
2) status=OK needs to be sent as a string, otherwise it will try to read "OK" as a boolean data type.

**Comment by bojand** [comment]
Hello, thanks for reporting this issue. I am not an expert InfluxDB user and do not use it frequently, so it seems this wasn't implemented properly, even though I remember testing it originally 🤷‍♂️ .

This should be addressed in [v0.24.0](https://github.com/bojand/ghz/releases/tag/v0.24.0). 

For example a detail line:
```
curl -i -XPOST 'http://localhost:8086/write?db=ghz' --data-binary 'ghz_detail,name="Greeter\ SayHello",proto="./greeter.proto",call="helloworld.Greeter.SayHello",host="0.0.0.0:50051",n=200,c=50,qps=0,z=0,timeout=20,dial_timeout=10,keepalive=0,data="{\"name\":\"Bob\ Smith\"}",metadata="",tags="{\"created\ by\":\"Joe\ Developer\"\,\"env\":\"staging\"}",hasError=false latency=43508356,error="",status="OK" 1548119987953596000'
```

And summary:
```
curl -i -XPOST 'http://localhost:8086/write?db=ghz' --data-binary 'ghz_run,name="Greeter\ SayHello",proto="./greeter.proto",call="helloworld.Greeter.SayHello",host="0.0.0.0:50051",n=200,c=50,qps=0,z=0,timeout=20,dial_timeout=10,keepalive=0,data="{\"name\":\"Bob\ Smith\"}",metadata="",tags="{\"created\ by\":\"Joe\ Developer\"\,\"env\":\"staging\"}",errors=4,has_errors=true count=200,total=202468959,average=35729591,fastest=25432955,slowest=65454407,rps=987.81,median=35300519,p95=56490139,errors=4 1548119963724582000'
```

Let me know if there are more issues and feel free to open new requests.
