### ISSUE TITLE
TLS: no way to provide client cert/key

### ISSUE THREAD

**Issue by srenatus** [bojand/ghz#55]
### Proto file(s)

None

### Command line arguments / config

None

### Expected Behavior

Given a gRPC setup where both the client and the server are required to provide a TLS cert, and given the root CA cert, as well as a cert/key pair for the client, I would like to be able to use `ghz` to benchmark the service's performance.

### Actual Behavior

I can provide a root CA cert using `-cert`, and I can provide a server name override using `-cname`, but there's no way to set a client cert/key.

### Steps to Reproduce (including precondition)

Have a server that requires the client to provide a TLS cert, and try to use ghz with it.

Sorry, this is brief -- It could be fleshed out, if need be; please let me know if this already is supported in some way I haven't found.

### Your Environment

- OS: Darwin
- ghz version: 0.24.0

**Comment by bojand** [comment]
Hello, the documentation in README file and in `-h` is slightly incorrect it seems 🤦‍♂️ . `-cert` is for the client certificate and we would use [NewClientTLSFromFile()](https://godoc.org/google.golang.org/grpc/credentials#NewClientTLSFromFile) in that case. If left blank but without `-insecure`, we would use the default root certificate (ie `credentials.NewClientTLSFromCert(nil, "")`). insecure is used IFF `-insecure` is used. Regardless I see the issue in that we are missing a way to specify root cert. Will fix this soon.

**Comment by srenatus** [comment]
For supplying the client's TLS cert, I'd expect this to take three arguments `--client-cert`, `--client-key`, and `--cert` (or rather `--ca-cert` for clarity?) and do something along the lines [described here](https://bbengfort.github.io/programmer/2017/03/03/secure-grpc.html), using [`credentials.NewTLS`](https://godoc.org/google.golang.org/grpc/credentials#NewTLS) to also add the client cert/key into the dial options. 😃

**Comment by srenatus** [comment]
☝️ PR merged. Thank you. Closing this 😃

**Comment by bojand** [comment]
Should be in version [v0.25.0](https://github.com/bojand/ghz/releases/tag/v0.25.0). Thanks for drawing my attention to this and feel free to report any more issues.

**Comment by srenatus** [comment]
Thank you for being so quick with this. 👍

**Comment by srenatus** [comment]
@bojand I think I must be doing something wrong, still:

```
# /src/ghz -protoset gateway.protoset -cert service.crt -key service.key -cacert root_ca.crt -cname gateway -call gateway.api.users.UsersMgmt/GetUsers 10.0.2.15:2001
could not load client key pair: open : no such file or directory
#
```

Can you spot something there? 😃

**Comment by bojand** [comment]
🤦‍♂️ Please try [v0.26.0](https://github.com/bojand/ghz/releases/tag/v0.26.0). Will improve this soon and add automated tests for CLI arguments.

**Comment by srenatus** [comment]
Works like a charm. Thanks! 😃
