### ISSUE TITLE
Is there a way to provide grpc call options like MaxCallRecvMsgSize

### ISSUE THREAD

**Issue by ananyashandilya1102** [bojand/ghz#69]
I would like to increase the default size that can be received by the API that I am testing. Is there a way to provide this as a CLI option?

**Comment by bojand** [comment]
Hello, thanks for submitting this issue. This is not possible right now. Will look into adding this.

**Comment by bojand** [comment]
Should be supported in [0.99.0](https://github.com/bojand/ghz/releases/tag/v0.99.0).

New CLI options `--max-recv-message-size` and `--max-send-message-size` can be specified using [human readable value](https://pkg.go.dev/github.com/dustin/go-humanize#ParseBytes) such as `42 MB`.

There is a new API `WithDefaultCallOptions()` which can be used to specify the default call options (including max sizes).
