### ISSUE TITLE
arguments -o and -O not working

### ISSUE THREAD

**Issue by UJtriumphs** [bojand/ghz#70]
### Command line arguments / config
./ghz -proto <PATH> -call com.proto.test.pingPong -skipTLS -insecure -D <REQUEST_PATH> -c 10 -n 200 localhost:8080 -O "csv" -o <PATH_TO_CSV>

### Expected Behavior
Create the file if not exist and save the output in that file in csv format

### Actual Behavior
Nothing happens, shows output in stdout

### Steps to Reproduce (including precondition)
Run the command

### Your Environment
- OS: Ubuntu 16.04
- ghz version: 0.30.0

**Comment by bojand** [comment]
Hello can you please comment on what was the issue so I can perhaps address it with better documentation or code change if needed. Thanks.
