### ISSUE TITLE
Works on Mac but not on Windows

### ISSUE THREAD

**Issue by myeveryheart** [bojand/ghz#78]
### Proto file(s)
{
  "proto": "xxxxx/user.proto",
  "call": "user.User.GetVerificationCode",
  "n": 20,
  "c": 5,
  "d": {
      "mobile": "1"
  },
  "insecure": true,
  "host": "192.168.1.95:50051"
}
### Command line arguments / config
xxx/ghz  -config xxx/config.json

### Expected Behavior
`Summary:
  Count:	20
  Total:	79.92 ms
  Slowest:	48.07 ms
  Fastest:	8.89 ms
  Average:	19.70 ms
  Requests/sec:	250.26

Response time histogram:
  8.886 [1]	|∎∎∎
  12.804 [12]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  16.722 [0]	|
  20.641 [0]	|
  24.559 [2]	|∎∎∎∎∎∎∎
  28.477 [0]	|
  32.396 [0]	|
  36.314 [2]	|∎∎∎∎∎∎∎
  40.232 [0]	|
  44.150 [0]	|
  48.069 [3]	|∎∎∎∎∎∎∎∎∎∎

Latency distribution:
  10% in 9.06 ms
  25% in 9.72 ms
  50% in 12.05 ms
  75% in 35.45 ms
  90% in 48.01 ms
  95% in 48.07 ms
  0% in 0 ns
Status code distribution:
  [OK]   20 responses`

### Actual Behavior
`Summary:
  Count:        20
  Total:        19.09 s
  Slowest:      0 ns
  Fastest:      0 ns
  Average:      0 ns
  Requests/sec: 0.00

Response time histogram:

Latency distribution:
Status code distribution:
  [Unavailable]   20 responses

Error distribution:
  [5]    rpc error: code = Unavailable desc = transport is closing
  [15]   rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>`

Hi, I get the right result on Mac, but I can't run it on Windows. (version v0.31.0)

**Comment by bojand** [comment]
Hello, hmm as far as I know it should work fine on Windows. Unfortunately it's not an OS I have access to or can easily test on. Will try to investigate some more in the future if I can.

**Comment by myeveryheart** [comment]
Hi I just figure it out that It's my problem.
By the way, awesome tool~
