### ISSUE TITLE
ghz command line vs ghz code output difference

### ISSUE THREAD

**Issue by shahankit783** [bojand/ghz#81]
Hi @bojand ,

I am using ghz tool for single channel performance testing. I am also looking into github code and running this code.

Now I am getting different output when I am running from binary file and from source code. 
**Binary File Running input**
ghz  -config config.json

**Output**
![image](https://user-images.githubusercontent.com/7392354/55324215-0449f600-549f-11e9-8b85-25d146301072.png)

**Source Code Running input**
go run cmd/ghz/main.go cmd/ghz/config.go  -config  config.json

**Output**
![image](https://user-images.githubusercontent.com/7392354/55324262-25124b80-549f-11e9-90d0-f0a804ca65b6.png)

As you can see here that I am getting big difference in both the results. So I want to know what is happening and which once is accurate.

**Note:** I am not changing your source code while running it

- OS: MacOS 10.13.1
- ghz version:0.30.0

**Comment by bojand** [comment]
Hello,

What version of Go are you using? Are you using `GOPATH` or go modules? What are all the config parameters? Is the server running locally or remote? What is the gRPC server implemented in. Are you sure the measurements are not accurate, and that there indeed should not be such a variability in response times? Note that the responses in the `go run ...` test have a large variability within themselves (from `174 ms` to `1391 ms`), whereas there is hardly any variability in the binary `ghz` test (all within `~450 ms`). This to me is also somewhat suspect. I would also recommend increasing the total # of requests (`-n` parameter) to increase the sample size.

Unfortunately I am not able to reproduce results using the two different execution mechanisms that exhibit such a drastic change in measurements. It would be helpful if you could provide a working example that demonstrates this behaviour complete with a proto file and sample server implementation. Either way I would think the precompiled binary `ghz` that you download from the releases page should be accurate.

**Comment by ankitonedirect** [comment]
**Go version**:go version go1.12.1 darwin/amd64
I am using go module not GOPATH
**Config params:**
{   "protoset" : "/Users/Downloads/bundle.protoset",
    "call": "package.service/Method",
    "n": 10,
    "c": 10,
    "d": {
        "cart_uid" : "0bcf878bf0-0904-4d6f-8bf6-cc6151e277d80000",
        "user_uid" : "G0jLbop00Zl2eDFpJH0TXK"
    },
    "host": "<server address>",
    "insecure": true,
    "T":1000,
    "t":50,
    "x":"10m",
    "z":"10m"
}
- Server is running remotely
- gRPC is implemented in java

Can you tell me what exactly you mean by this 

**Note that the responses in the go run ... test have a large variability within themselves (from 174 ms to 1391 ms), whereas there is hardly any variability in the binary ghz test (all within ~450 ms)**

**Comment by bojand** [comment]
With the `go run ...` command the resulting measurement of response times cover a wide range of values. The fastest response time is `174 ms` while the slowest response time is `1391 ms`. However, in the other scenario when using the downloaded `ghz` binary, there is a very small variance in the reported measurement values. All the values are in `450-ish ms` range, fastest being `455 ms` and the slowest being `459 ms`. There seems to be a significant discrepancy in general behaviour of the service at test, one having produced much more consistent results, and the other inconsistent highly variable measurements. If you are running this against an actual instance of a service in a deployed environment that could be handling actual requests from other sources, many factors could be at play such as network and load on the server.

**Comment by shahankit783** [comment]
@bojand
I try to run 3 different things. 

1) Executable binary available on https://github.com/bojand/ghz/releases
![image](https://user-images.githubusercontent.com/7392354/55402597-73901a80-5571-11e9-9148-60ef87a2d792.png)

2) Run ghz using go command from this source code
https://github.com/bojand/ghz

![image](https://user-images.githubusercontent.com/7392354/55402633-899ddb00-5571-11e9-85f5-b39911b77027.png)

3) And I have generated ghz binary from this source code

![image](https://user-images.githubusercontent.com/7392354/55402669-9cb0ab00-5571-11e9-9209-5fd0c3e157b1.png)

All this commands with same server configuration. But getting all different output with huge difference
It would be really great if you spare little time and check my configuration via anything skype/GTM or any tool at your convenient time.

Thank you so much !!!

**Comment by bojand** [comment]
Hello, do you observe the same behaviour if you run the service locally and run the test against local running instance using the two different methods, thus factoring out netowork and other requests the service may be handling. What about running against a simpler [hello world](https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto) example both locally and deployed? Does the same issue persist? You can find sample code in gRPC documentation and repository.
