### ISSUE TITLE
Unary call mode with array of 1000 messages of JSON format consumes all CPU

### ISSUE THREAD

**Issue by egick666** [bojand/ghz#88]
**Proto file(s)**

**DecisionServiceProto.proto definition:**

message Decision {
    string interactionId = 1;
    string timestamp = 2;
    string decisionTable = 3;
    string decisionTableRule = 4;
    string action = 5;
    repeated com.avaya.ept.turing.configuration.commondata.RoutingPoint routingPoints = 6;
}

enum Channel {
    Voice = 0;
};

message MakeDecisionRequest {
    DecisionTableCommonRequest decisionTableRequestParameters = 1;
    string interactionId = 2;
    string from = 3;
    string to = 4;
    Channel channel = 5;
    map<string, string> params = 6;
}

service DecisionService {
    rpc MakeDecision (MakeDecisionRequest) returns (Decision) {
    }
}

**CommonMessagesProto.proto definition:**

message DecisionTableCommonRequest {
    string tenantId = 1;
    string name = 2;
}

message Tenant {
    string tenantId = 1;
}

message Report {
    string status = 1;
    string message = 2;
}

**Command line arguments / config**
./ghz --proto=./DecisionServicesProto.proto --call=com.avaya.ept.turing.bre.DecisionService.MakeDecision -D ./request_files/requests_1000_rand.json -c 28 -q 10 -z 1m --insecure 192.168.37.248:50041

**Describe the bug**
I'm using ghz in **unary** call mode with **array of request messages** provided in **JSON format** to test performance of my gRPC server. 
Total number of messages in array - **1000**.

After running the command above I'm facing 100% CPU consumption on all the 4 cores of CPU. This affects real query per second results as well as response time so that such tests has no any sense because of client bottleneck (server processes request much faster than client able to generate them and shows CPU consumption under 10%). Server is running on a dedicated VM that ghz.

ghz is running on a dedicated VM (no any other resource consuming applications are running) with 4 vCPUs allocated for this VM running on Xeon(R) CPU X5670 @ 2.93GHz.

**htop** tool is used to monitor CPU consumption.

The following test summary appears after 1m of test duration:
**Summary:**
  Count:        600
  Total:        61.33 s
  Slowest:      873.45 ms
  Fastest:      2.06 ms
  Average:      265.89 ms
  Requests/sec: 9.78

As you may see requests/sec is about 10 but should be around 280

**To Reproduce**
Run htop on server VM.
Run htop on ghz client VM
Run ghz cli command above with 1000 messages in array of JSON format.

**Expected behavior**
Server side htop shows CPU consumption under 10% during test
Client side htop shows CPU consumption under 10% during test
Requests/sec in summary is close to specified qps (about 280)

**Environment**
 - OS: CentOS Linux release 7.4.1708 (Core) X64
 - ghz: 0.36.0
 
**Screenshots**
htop output is attached:
![ghz_cpu_utilization](https://user-images.githubusercontent.com/20224376/56866421-90d5ce80-69e1-11e9-8b0a-529ea41cb330.png)

**Additional context**
There is no such issue with unary call mode using array of messages in **binary format**, CPU is consumed below 10%

**Comment by bojand** [comment]
Hello, can you give [0.37.0-pre.0](https://github.com/bojand/ghz/releases/tag/v0.37.0-pre.0) a try please. In my testing the same test run that before consumed 100% when I reproduced the issue now consumed no more than ~22%. A test with same params as above (ie `-z 1m -c 28 -q 10`) and `1000` JSON objects now consumes ~15-16 %. Give the prerelase a try and let me know if you see improvements. Thanks.

**Comment by bojand** [comment]
Hello @egick666, have you had a chance to test this?
Thanks,

**Comment by egick666** [comment]
Hi @bojand 
Sorry, I haven't yet. I'll try to run this week and let you know results.

Thanks

**Comment by bojand** [comment]
Hello, thanks! No rush just wanted to ping you in case you didn't notice it originally, or forgot about it.

**Comment by egick666** [comment]
Hi @bojand 

Sorry for such a long silence. I was able to test your RC version running 2500 json messages in array and it was consuming about 22% of CPU. I guess it's fine now.

Thanks for a great job and lightning fast response with this issue.

**Comment by bojand** [comment]
Hello, great! Thanks for confirming this improves the performance. This has been released in [0.37.0](https://github.com/bojand/ghz/releases/tag/v0.37.0).
