### ISSUE TITLE
Do ghz use connections again?

### ISSUE THREAD

**Issue by ohs30359-nobuhara** [bojand/ghz#89]
Do ghz use connections again?

I'm assuming testing of cases requested by multiple clients.
However, if the connection is reused, correct testing can not be performed.

**Comment by bojand** [comment]
By default ghz uses a single connection and all concurrency is performed using goroutines that share this single connection. Number of connections can be controlled using [`--connections`](https://ghz.sh/docs/options#connections) flag.

**Comment by ohs30359-nobuhara** [comment]
Thank you!
It seems that I can solve what I want to do!
