### ISSUE TITLE
transport: authentication handshake failed: EOF when supplied certificates

### ISSUE THREAD

**Issue by yeshwanthvshenoy** [bojand/ghz#90]
**Proto file(s)**
As in GRPC Java Hello World TLS from [here](https://github.com/grpc/grpc-java/tree/master/examples/example-tls)

**Command line arguments / config**
./ghz --cacert=/tmp/sslcert/ca.crt --cert=/tmp/sslcert/client.crt --key=/tmp/sslcert/client.pem --proto ./jdk11/src/main/proto/helloworld/helloworld.proto --call helloworld.Greeter.SayHello -d '{"name":"world"}' -n 2000 -c 20 --connections=10 localhost:8071

**Describe the bug**
Took the exact same example from the repository without any changes. I then generated certificates necessary in my `/tmp/sslcert` as you can see. I dockerized the example on latest ubuntu with jdk8. That's all and I am not able to run ghz.

**To Reproduce**
Take same example from above, run it in docker and try the same command.

**Expected behavior**

**Environment**
 - OS: macOS 10.14.4
 - ghz: 0.36.0
 
**Screenshots**
Not necessary.

**Additional context**
Logs if this helps:
```
mac:Downloads yeshwanths$ ./ghz --cacert=/tmp/sslcert/ca.crt --cert=/tmp/sslcert/client.crt --key=/tmp/sslcert/client.pem --proto ./example-tls/src/main/proto/helloworld/helloworld.proto --call helloworld.Greeter.SayHello -d '{"name":"world"}' -n 2000 -c 20 --connections=10 localhost:8071

Summary:
  Count:	2000
  Total:	32.88 ms
  Slowest:	0 ns
  Fastest:	0 ns
  Average:	0 ns
  Requests/sec:	0.00

Response time histogram:

Latency distribution:

Status code distribution:
  [Unavailable]   2000 responses   

Error distribution:
  [2000]   rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: EOF"```

**Comment by yeshwanthvshenoy** [comment]
Forgot to mention:
The script is not able to connect to docker. However, when same application is run outside docker works totally fine. Doesn't this feel weird?

**Comment by bojand** [comment]
Hello, thanks for opening this issue, I'll try and look into this. Please provide some more information. Specifically how is the server run as it seems to accept command line arguments? Also provide more information how the docker is created and run. For example make sure you're allowing / mapping ports properly. As well I would suggest that the server within the the Docker is started listenning on `0.0.0.0` because containers do not default to exposing mapped ports to `localhost`.

**Comment by yeshwanthvshenoy** [comment]
Apparently, there was an issue with my GRPC server and hence thats why it wasnt working when I exposed the port from docker. I have resolved it. Thanks for the support!

**Comment by bath** [comment]
For anyone else stumbling upon this, I also had this issue. I dockerized my program that held the grpc listen server and needed to change the listen address from localhost to 0.0.0.0 so a seperate dockerized program could establish a connection to it. also ensure that you copy the cert the GRPC server generates for your other programs.

**Comment by LaurentTreguier** [comment]
@bath thank you so much, I stumbled upon this issue minutes ago, and I'm fairly certain you just saved me hours of wondering what's wrong!
