### ISSUE TITLE
Question on ghz behaviour: does it wait for a request to complete before sending a new request?

### ISSUE THREAD

**Issue by arinto** [bojand/ghz#93]
Hi @bojand, I have question to confirm my understanding. 

Does ghz waits for a request to complete before sending a new request when we don't specify the rate limit option (`-q`)? 

My understanding is no, but correct me if my wrong. 
In other words, ghz will try as fast as possible in sending requests when we don't specify the rate limit option (`-q`).

**Comment by bojand** [comment]
Hello, each goroutine worker (`concurrency` option specifies the number of workers) makes its share of total requests. These requests are done in series and to completion before the next one is sent. 

When `-q` option is used we try to limit the requests in each worker to match that request rate. This essentially spaces out the requests by adding a timeout to each worker before it attempts each call.

Hope this helps.

**Comment by arinto** [comment]
Thank @bojand for the clarification!
