### ISSUE TITLE
several calls

### ISSUE THREAD

**Issue by vvitaly1** [bojand/ghz#95]
Hello.

Thanks for the greate tool.
Can you please look into adding several method calls inside one session (like authorizing in grpc session and then do several calls in the same session).

Thanks again

**Comment by bojand** [comment]
Hello,

Similar questions have been [asked before](https://github.com/bojand/ghz/issues/65). There is no really easy way to accomplish this using the CLI. My suggestion would be to script a test using the [Go package API](https://godoc.org/github.com/bojand/ghz). Alternatively you may be able to accomplish something using one of the other [testing tools](https://github.com/grpc-ecosystem/awesome-grpc#tools-test) such as [hazana](https://github.com/emicklei/hazana) perhaps (note I have never used it). Hope this helps!
