### ISSUE TITLE
Question: How can we substitute data in the fields dynamically in data file or meta file

### ISSUE THREAD

**Issue by sauravkumar05** [bojand/ghz#96]
I went through the options and I understand that we can send the data file and meta file as an options. Is there any way to substitute a key in the json with some automatically data population like random request id and timestamp that gets set when the rpc call is made.

**Comment by bojand** [comment]
Hello, yes this can be achieved using [call template data](https://ghz.sh/docs/calldata) functionality. Just set your metadata file to have the templates and they will be filled in for you.

```json
{
  "request-id": "{{.RequestNumber}}",
  "timestamp": "{{.TimestampUnix}}"
}
```

Note that request number is not random, but will be unique for each call invocation / request.

**Comment by sauravkumar05** [comment]
Thank you that was very helpful . So I was looking at different options where concurrency will create that many go routines and you have to define total number and qps.. I want to generate more than 10k request per second with only 10 client connections any suggestions how can I do that .. I have a 72 core machine but I didn’t see that made a difference by adding the cpu option.

-c 4000 -z 1m —connections 10 -qps 10000 —cpu 70

Max I was probably able to see is around d

**Comment by bojand** [comment]
Hello

All `qps` does is try to space out the requests using a timeout to try and get that QPS value. It's more useful for limiting the QPS. With a qps of 10000 qps we would space out each request within each worker with 100µs pause / timeout. 

The RPS in results is a theoretical computed RPS computed by taking the total number of requests (successful and failed) in the test and dividing it by the total duration of the test. That is the total count / total time.

To test as fast as the server will go I would suggest just leaving out the `qps` param.

Hope this helps.

**Comment by amit-traiana** [comment]
Hi there,

On the code I'm working on - each gRPC request create a persistent database entry. So once an entity was created, I can no longer create it with the same name. Using `TimestampUnix` is not good enough because multiple workers will output the same Timestamp and while `RequestNumber` will work the first time, I will be forced to clean the data for the next run to work. Is there a way to generate a completely unique string? UUID of some sort?

Thanks!
